import type { LandingPageContent, SiteDocumentKey } from '@/types/site-content-cms';

export type LandingPageKey = Extract<SiteDocumentKey, 'rooms' | 'experiences' | 'transfers' | 'explore-koman' | 'gallery'>;
export const landingPageKeys: LandingPageKey[] = ['rooms', 'experiences', 'transfers', 'explore-koman', 'gallery'];

const common = ['eyebrow', 'heading', 'description', 'heroImageId', 'heroImageAlt', 'introEyebrow', 'introHeading', 'introDescription'];
export const landingPageFieldNames: Record<LandingPageKey, string[]> = {
  rooms: [...common, 'detailEyebrow', 'detailHeading', 'relatedEyebrow', 'relatedHeading', 'relatedLinkLabel'],
  experiences: [...common, 'ctaEyebrow', 'ctaHeading', 'ctaDescription', 'ctaLabel', 'ctaTarget', 'detailEyebrow', 'detailHeading', 'relatedEyebrow', 'relatedHeading', 'relatedDescription', 'relatedLinkLabel'],
  transfers: [...common, 'processEyebrow', 'processHeading', 'processStep1Title', 'processStep1Description', 'processStep2Title', 'processStep2Description', 'processStep3Title', 'processStep3Description', 'ctaEyebrow', 'ctaHeading', 'ctaDescription', 'ctaLabel', 'ctaTarget', 'detailEyebrow', 'detailHeading'],
  'explore-koman': common,
  gallery: common,
};

export const landingPageDefaults: Record<LandingPageKey, LandingPageContent> = {
  rooms: { eyebrow: 'Stay at Borealis', heading: 'Rooms made for slower mornings.', description: 'Thoughtful comfort, natural textures and the landscape just beyond your window.', heroImage: '', heroImageAlt: 'A warm Borealis guest room', introEyebrow: 'Choose your room', introHeading: 'Space to settle in.', introDescription: '', ctaEyebrow: '', ctaHeading: '', ctaDescription: '', ctaLabel: '', ctaTarget: '', detailEyebrow: 'The room', detailHeading: 'A calm place to come back to.', relatedEyebrow: 'More ways to stay', relatedHeading: 'Other rooms at Borealis.', relatedLinkLabel: 'View all rooms' },
  experiences: { eyebrow: 'Experience Koman', heading: 'Let the landscape lead.', description: 'Time on the water, local perspectives and slower ways to discover the nature around Borealis.', heroImage: '', heroImageAlt: 'Experience the landscape around Koman', introEyebrow: 'Choose your experience', introHeading: 'More than a place to stay.', introDescription: 'Choose from the experiences currently published by Borealis.', ctaEyebrow: 'Add to your stay', ctaHeading: 'Already choosing a room?', ctaDescription: 'Experiences can be requested independently or added while creating a room booking.', ctaLabel: 'Start a booking', ctaTarget: '/book', detailEyebrow: 'The experience', detailHeading: 'Time well spent in Koman.', relatedEyebrow: 'Make a stay of it', relatedHeading: 'Come back to comfort.', relatedDescription: 'Pair your time outside with a quiet room by the lake.', relatedLinkLabel: 'Explore all rooms' },
  transfers: { eyebrow: 'Transfers by Borealis', heading: 'The simple way to reach the lake.', description: 'Request a transfer as part of your stay, with one clear journey from pickup to Borealis—or onward to your next destination.', heroImage: '', heroImageAlt: 'Journey to Borealis Guest House', introEyebrow: 'Available routes', introHeading: 'Choose where you are coming from.', introDescription: 'Browse current routes, journey details and prices managed directly by Borealis.', processEyebrow: 'How it will work', processHeading: 'A clearer arrival.', processStep1Title: 'Choose a route', processStep1Description: 'Select the connection that fits your journey.', processStep2Title: 'Add your details', processStep2Description: 'Share timing and passenger information.', processStep3Title: 'Receive confirmation', processStep3Description: 'Final service details will be confirmed directly.', ctaEyebrow: 'Travelling a different route?', ctaHeading: 'Tell us where you need to go.', ctaDescription: 'The route model supports additional origins and destinations. Ask about a connection that is not listed yet.', ctaLabel: 'Request another route', ctaTarget: '/contact', detailEyebrow: 'Route details', detailHeading: 'A straightforward journey.' },
  'explore-koman': { eyebrow: 'The local guide', heading: 'Koman is more than a crossing.', description: 'Practical notes and slower stories for travellers who want to understand this remarkable corner of Albania.', heroImage: '', heroImageAlt: 'The landscape around Koman, Albania', introEyebrow: 'Field notes', introHeading: 'Know before you go.', introDescription: '', ctaEyebrow: '', ctaHeading: '', ctaDescription: '', ctaLabel: '', ctaTarget: '' },
  gallery: { eyebrow: 'The visual story', heading: 'A sense of life by the lake.', description: 'Rooms, water, mountain paths and quiet outdoor moments—an evolving visual journal of Borealis.', heroImage: '', heroImageAlt: 'Borealis Guest House and its surroundings', introEyebrow: 'Borealis in pictures', introHeading: 'Look a little closer.', introDescription: 'Select an image to open the full gallery. Swipe on touch screens or use the arrow keys.', ctaEyebrow: '', ctaHeading: '', ctaDescription: '', ctaLabel: '', ctaTarget: '' },
};

export function isLandingPageKey(value: string): value is LandingPageKey { return landingPageKeys.includes(value as LandingPageKey); }
