import { fetchPublicCms } from '@/lib/supabase/public-cms';
import 'server-only';
import type {Metadata}from'next';
import{cache}from'react';
import{createClient}from'@supabase/supabase-js';
import{getGlobalSeo}from'@/services/global-seo';
import type{SEOData}from'@/types/public';
import type{SeoPageKey}from'@/types/seo-admin';
import{getEntityTranslationMap,getHreflangAlternates,getLanguageContext}from'@/services/translations';

export function createMetadata(seo:SEOData,path:string,siteName='Borealis Guest House'):Metadata{const title=seo.title,description=seo.description,ogTitle=seo.ogTitle||title,ogDescription=seo.ogDescription||description,image=seo.image;return{title,description,alternates:{canonical:seo.canonical||path},robots:seo.noindex?{index:false,follow:true}:undefined,openGraph:{type:'website',siteName,title:ogTitle,description:ogDescription,url:seo.canonical||path,images:image?[{url:image,alt:ogTitle}]:[]},twitter:{card:'summary_large_image',title:ogTitle,description:ogDescription,images:image?[image]:[]}}}

const defaults:Record<SeoPageKey,{path:string;title:string;description:string}>={homepage:{path:'/',title:'Borealis Guest House | Lakeside Stay in Koman',description:'Stay by Koman Lake at Borealis Guest House. Discover rooms, local experiences and convenient transfers.'},rooms:{path:'/rooms',title:'Rooms',description:'Explore comfortable rooms by Koman Lake at Borealis Guest House.'},experiences:{path:'/experiences',title:'Experiences',description:'Discover lake and nature experiences from Borealis in Koman.'},transfers:{path:'/transfers',title:'Transfers',description:'Plan private transfers to Borealis Guest House and destinations around Koman.'},'explore-koman':{path:'/explore-koman',title:'Explore Koman',description:'Practical, thoughtful guides to Koman Lake and the surrounding region.'},about:{path:'/about',title:'About Borealis',description:'Discover the story, setting and hospitality behind Borealis Guest House in Koman.'},contact:{path:'/contact',title:'Contact Borealis',description:'Contact Borealis Guest House about rooms, transfers, experiences and directions to Koman.'}};

export const getPageSeo=cache(async(key:SeoPageKey):Promise<SEOData&{path:string}>=>{const fallback=defaults[key],global=await getGlobalSeo(),url=process.env.NEXT_PUBLIC_SUPABASE_URL,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!anon)return{...fallback,image:global.defaultOgUrl};try{const db=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false},global:{fetch:fetchPublicCms}}),{data}=await db.from('page_seo').select('id,slug,seo_title,meta_description,og_title,og_description,og_image_id,canonical_override,noindex').eq('page_key',key).eq('status','published').maybeSingle();if(!data)return{...fallback,image:global.defaultOgUrl};const translations=await getEntityTranslationMap('page_seo',[data.id]),t=translations.get(data.id)||{};let image=global.defaultOgUrl;if(data.og_image_id){const{data:asset}=await db.from('media_assets').select('file_path').eq('id',data.og_image_id).eq('status','published').maybeSingle();if(asset)image=`${url}/storage/v1/object/public/public-media/${asset.file_path}`}return{path:data.slug?`/${data.slug}`:'/',title:t.seo_title||data.seo_title||fallback.title,description:t.meta_description||data.meta_description||global.defaultDescription||fallback.description,ogTitle:t.og_title||data.og_title||undefined,ogDescription:t.og_description||data.og_description||undefined,image,canonical:data.canonical_override||undefined,noindex:data.noindex}}catch{return{...fallback,image:global.defaultOgUrl}}});
export async function createLocalizedMetadata(seo:SEOData,path:string,siteName='Borealis Guest House'):Promise<Metadata>{const metadata=createMetadata(seo,path,siteName),[languages,context]=await Promise.all([getHreflangAlternates(path),getLanguageContext()]);metadata.alternates={canonical:seo.canonical||path,languages};if(metadata.openGraph&&context.selected?.code)metadata.openGraph.locale=context.selected.code.replace('-','_');return metadata}
export async function createPageMetadata(key:SeoPageKey):Promise<Metadata>{const[seo,global]=await Promise.all([getPageSeo(key),getGlobalSeo()]);return createLocalizedMetadata(seo,seo.path,global.siteName)}
