import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireAdmin } from '@/lib/admin/auth';
import { adminBookingsRepository } from '@/lib/repositories/admin/bookings';
import { AdminPageHeader, StatusBadge } from '@/components/admin/ui';
import { formatMoney } from '@/lib/pricing/format';
import { changeBookingStatus, saveBookingNote } from '../actions';
import { BookingStatusForm } from '@/components/admin/BookingStatusForm';

export default async function BookingPage({params}:{params:Promise<{id:string}>}){
  const{id}=await params,session=await requireAdmin(['owner','manager','staff']),booking=await adminBookingsRepository.get(session,id);if(!booking)notFound();
  const allowed=adminBookingsRepository.allowed(booking.status),hasRoom=booking.items.some(item=>item.type==='room'),nights=booking.checkIn&&booking.checkOut?Math.round((new Date(`${booking.checkOut}T00:00:00Z`).getTime()-new Date(`${booking.checkIn}T00:00:00Z`).getTime())/86400000):0;
  const description=hasRoom&&booking.checkIn&&booking.checkOut?`${booking.checkIn} → ${booking.checkOut}`:`${booking.bookingType} · ${booking.serviceDate||'date not set'}${booking.serviceTime?` at ${booking.serviceTime}`:''}`;
  return <div className="space-y-7"><AdminPageHeader title={booking.reference} description={description} actions={<Link href="/admin/bookings" className="inline-flex min-h-11 items-center justify-center rounded-lg border border-slate-300 bg-white px-4 text-sm font-bold">Back to bookings</Link>}/><div className="grid gap-6 lg:grid-cols-[1fr_22rem]"><div className="space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{booking.bookingType} booking</h2><StatusBadge status={booking.status}/></div><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Fact label="Reference" value={booking.reference}/><Fact label="Source" value={booking.source}/><Fact label="Created" value={new Date(booking.createdAt).toLocaleString()}/>{hasRoom&&<><Fact label="Room" value={booking.room}/><Fact label="Check-in" value={booking.checkIn}/><Fact label="Check-out" value={booking.checkOut}/><Fact label="Nights" value={String(nights)}/><Fact label="Adults" value={String(booking.adults)}/><Fact label="Children" value={String(booking.children)}/></>}</dl></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Guest</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Fact label="Name" value={booking.guestName}/><Fact label="Email" value={booking.email}/><Fact label="Phone" value={booking.phone||'Not provided'}/><Fact label="Country" value={booking.country||'Not provided'}/></dl>{booking.notes&&<div className="mt-5 border-t pt-5"><p className="text-xs font-bold uppercase text-slate-500">Guest note</p><p className="mt-2 whitespace-pre-wrap text-sm">{booking.notes}</p></div>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">{hasRoom?'Complete package':'Booking items'}</h2><div className="mt-4 divide-y">{booking.items.map(item=><div key={item.id} className="flex justify-between gap-4 py-4"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">{item.type}</p><strong>{item.title}</strong><p className="mt-1 text-xs text-slate-500">{item.type==='room'?`Quantity ${item.quantity}`:<>{item.serviceDate}{item.serviceTime?` at ${item.serviceTime}`:''} · {item.requestedQuantity} {item.type==='transfer'?'passenger(s)':'participant(s)'}</>} · {item.status}</p><p className="mt-1 text-xs text-slate-500">{formatMoney(item.unitPrice,booking.currency)} {item.quantity>1?'each':''}</p></div><span className="font-semibold">{formatMoney(item.totalPrice,booking.currency)}</span></div>)}</div><dl className="space-y-2 border-t pt-5 text-sm">{hasRoom&&<Price label="Room subtotal" value={booking.roomSubtotal} currency={booking.currency}/>}<Price label={hasRoom?'Experiences and transportation':'Service subtotal'} value={booking.addonsSubtotal} currency={booking.currency}/>{booking.discount>0&&<Price label="Discount" value={-booking.discount} currency={booking.currency}/>}<Price label="Taxes and fees" value={booking.taxes} currency={booking.currency}/></dl><div className="mt-5 flex justify-between border-t pt-5 text-lg font-bold"><span>Total</span><span>{formatMoney(booking.total,booking.currency)}</span></div></section>
  </div><aside className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Payment</h2><dl className="mt-4 space-y-3"><Fact label="Status" value={booking.paymentStatus.replaceAll('_',' ')}/><Fact label="Method" value={booking.paymentMethod.replaceAll('_',' ')||'Not selected'}/></dl></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Change status</h2>{allowed.length?<BookingStatusForm action={changeBookingStatus.bind(null,id)} allowed={allowed} reference={booking.reference}/>:<p className="mt-3 text-sm text-slate-500">This booking has no further lifecycle actions.</p>}</section><form action={saveBookingNote.bind(null,id)} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Internal note</h2><textarea name="internalNote" defaultValue={booking.internalNote} rows={7} className="mt-3 w-full rounded-lg border border-slate-300 p-3"/><button className="mt-3 min-h-11 w-full rounded-lg bg-slate-950 px-4 font-bold text-white">Save note</button></form></aside></div></div>;
}
function Fact({label,value}:{label:string;value:string|null}){return <div><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="mt-1 font-semibold capitalize">{value||'Not applicable'}</dd></div>}
function Price({label,value,currency}:{label:string;value:number;currency:string}){return <div className="flex justify-between"><dt className="text-slate-500">{label}</dt><dd>{formatMoney(value,currency)}</dd></div>}
