import{cache}from'react';import{cookies}from'next/headers';import{createClient as createSupabaseClient}from'@supabase/supabase-js';import type{LanguageRecord}from'@/types/languages';import{fetchSupabase}from'@/lib/supabase/fetch';
const createClient=(url:string,key:string,options:Parameters<typeof createSupabaseClient>[2])=>createSupabaseClient(url,key,{...options,global:{...options?.global,fetch:fetchSupabase}});
export interface PublicLanguageContext{selected:LanguageRecord|null;defaultLanguage:LanguageRecord|null;enabled:LanguageRecord[]}
const client=()=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null};
export const getPublicLanguages=cache(async():Promise<LanguageRecord[] >=>{const db=client();if(!db)return[];const{data,error}=await db.from('languages').select('id,code,label,native_name,icon_reference,enabled,is_default,sort_order').eq('enabled',true).order('sort_order');if(error)return[];return(data||[]).map(x=>({id:x.id,code:x.code,name:x.label,nativeName:x.native_name,icon:x.icon_reference||'',enabled:x.enabled,isDefault:x.is_default,sortOrder:x.sort_order}))});
export async function getLanguageContext(requestedCode?:string):Promise<PublicLanguageContext>{const enabled=await getPublicLanguages(),cookieStore=await cookies(),requested=requestedCode||cookieStore.get('borealis_language')?.value,defaultLanguage=enabled.find(x=>x.isDefault)||enabled[0]||null,selected=enabled.find(x=>x.code.toLowerCase()===requested?.toLowerCase())||defaultLanguage;return{selected,defaultLanguage,enabled}}
export async function getEntityTranslations(entityType:string,entityId:string,requestedCode?:string):Promise<{language:LanguageRecord|null;values:Record<string,string>}>{const context=await getLanguageContext(requestedCode),db=client();if(!db||!context.selected)return{language:context.selected,values:{}};const ids=Array.from(new Set([context.defaultLanguage?.id,context.selected.id].filter(Boolean)))as string[];const{data}=await db.from('translations').select('language_id,field_name,translated_value').eq('entity_type',entityType).eq('entity_id',entityId).eq('status','published').in('language_id',ids);const defaults=Object.fromEntries((data||[]).filter(x=>x.language_id===context.defaultLanguage?.id).map(x=>[x.field_name,x.translated_value])),selected=Object.fromEntries((data||[]).filter(x=>x.language_id===context.selected?.id).map(x=>[x.field_name,x.translated_value]));return{language:context.selected,values:{...defaults,...selected}}}
export async function getHreflangAlternates(path:string){const languages=await getPublicLanguages(),fallback=languages.find(x=>x.isDefault)||languages[0];return Object.fromEntries([...languages.map(language=>[language.code,`${path}${path.includes('?')?'&':'?'}lang=${encodeURIComponent(language.code)}`]),...(fallback?[['x-default',path]]:[])])}
export async function getEntityTranslationMap(entityType:string,entityIds:string[]):Promise<Map<string,Record<string,string>>>{const context=await getLanguageContext(),db=client(),result=new Map<string,Record<string,string>>();if(!db||!context.selected||!entityIds.length)return result;const languageIds=Array.from(new Set([context.defaultLanguage?.id,context.selected.id].filter(Boolean)))as string[];const{data}=await db.from('translations').select('language_id,entity_id,field_name,translated_value').eq('entity_type',entityType).eq('status','published').in('entity_id',entityIds).in('language_id',languageIds);for(const id of entityIds){const rows=(data||[]).filter(x=>x.entity_id===id),values=(languageId?:string)=>Object.fromEntries(rows.filter(x=>x.language_id===languageId&&x.translated_value?.trim()).map(x=>[x.field_name,x.translated_value]));result.set(id,{...values(context.defaultLanguage?.id),...values(context.selected.id)})}return result}
