import type{Metadata}from'next';
import Link from'next/link';
import{notFound}from'next/navigation';
import{ArticleBlocks}from'@/components/public/ArticleBlocks';
import{ExperienceGallery}from'@/components/public/ExperienceGallery';
import{BreadcrumbJsonLd,JsonLd}from'@/components/public/JsonLd';
import{Breadcrumbs,PublicShell}from'@/components/public/PageShell';
import{contentRepository}from'@/services/content';
import{createLocalizedMetadata}from'@/lib/seo';
import{getAdminSession}from'@/lib/admin/auth';

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params,item=await contentRepository.getArticle(slug);if(!item)return{title:'Article not found'};const metadata=await createLocalizedMetadata({title:item.seo.title,description:item.seo.description,image:item.seo.ogImage||item.image,canonical:item.seo.canonical,noindex:item.seo.noindex},`/explore-koman/${slug}`);return metadata}

export default async function Page({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{preview?:string}>}){
  const{slug}=await params,{preview}=await searchParams,session=preview?await getAdminSession():null,previewId=session?.role==='owner'?preview:undefined,item=await contentRepository.getArticle(slug,previewId);if(!item)notFound();
  const relatedIds=[...(item.relatedArticleIds||[]),...(item.relatedExperienceIds||[]),...(item.relatedTransferIds||[])],images=Array.from(new Set([item.image,...(item.featuredGallery||[]).map(image=>image.url)])),faqs=(item.blocks||[]).filter(block=>block.type==='faq').flatMap(block=>block.items||[]);
  return <PublicShell>{previewId&&<div className="bg-amber-100 px-4 py-2 text-center text-sm font-bold text-amber-900">Owner preview · unpublished content may be visible</div>}<BreadcrumbJsonLd items={[{name:'Home',url:'/'},{name:'Explore Koman',url:'/explore-koman'},{name:item.title,url:`/explore-koman/${slug}`}]}/><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:item.title,description:item.excerpt,image:images,author:item.author?{'@type':'Person',name:item.author}:undefined,datePublished:item.publishedAt||undefined}}/>{faqs.length>0&&<JsonLd data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(faq=>({'@type':'Question',name:faq.question,acceptedAnswer:{'@type':'Answer',text:faq.answer}}))}}/>}<article className="shell py-10"><Breadcrumbs items={[{label:'Home',href:'/'},{label:'Explore Koman',href:'/explore-koman'},{label:item.title}]}/><ExperienceGallery images={images} title={item.title}/><header className="mx-auto max-w-3xl pt-12"><p className="eyebrow">{item.category.name} · {item.readTime}</p><h1 className="mt-4 font-serif text-5xl leading-none text-lake md:text-7xl">{item.title}</h1>{item.subtitle&&<p className="mt-5 font-serif text-3xl leading-snug text-green">{item.subtitle}</p>}<p className="mt-6 text-xl leading-8 text-muted">{item.excerpt}</p>{(item.author||item.publishedAt)&&<p className="mt-5 text-sm text-muted">{item.author&&`By ${item.author}`}{item.author&&item.publishedAt?' · ':''}{item.publishedAt&&new Date(item.publishedAt).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</p>}</header><div className="mx-auto max-w-3xl py-10">{item.blocks?.length?<ArticleBlocks article={item}/>:item.body.map((value,index)=><p key={index} className="mb-6 text-lg leading-9 text-charcoal/80">{value}</p>)}{relatedIds.length>0&&<aside className="mt-14 border-t border-lake/10 pt-8"><p className="eyebrow">Continue exploring</p><div className="mt-4 grid gap-3">{relatedIds.flatMap(id=>{const related=item.related?.[id];return related?[<Link key={id} href={related.href} className="flex items-center justify-between rounded-xl bg-ivory p-4 font-bold text-lake"><span>{related.label}</span><span aria-hidden="true">→</span></Link>]:[]})}</div></aside>}</div></article></PublicShell>;
}
