import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {PublicShell} from '@/components/public/PageShell';
import {occupancyLabel} from '@/lib/booking/occupancy';
import {formatMoney} from '@/lib/pricing/format';
import {createServerSupabaseClient} from '@/lib/supabase/server';

export const metadata:Metadata={title:'Booking confirmation | Borealis Guest House',robots:{index:false,follow:false}};
type Occupancy={adults:number;children:number;infants:number};
type ConfirmationItem={type:string;title:string;quantity:number;unitPrice:number|string;subtotal:number|string;currency:string;date:string|null;time:string|null;status:string;metadata?:{requestedQuantity?:number;guestCount?:number;capacity?:number;occupancy?:Occupancy}};
type ConfirmationRow={reference:string;status:string;paymentStatus:string;paymentMethod:string|null;guestName:string;checkIn:string|null;checkOut:string|null;adults:number;children:number;infants:number|null;totalGuests:number|null;roomSubtotal:number|string;addonsSubtotal:number|string;taxes:number|string;discount:number|string;total:number|string;currency:string;items:ConfirmationItem[]};

export default async function BookingConfirmationPage({params}:{params:Promise<{token:string}>}){
  const{token}=await params;if(!/^[0-9a-f-]{36}$/i.test(token))notFound();
  const db=await createServerSupabaseClient(),{data,error}=await db.rpc('get_booking_confirmation_package',{target_token:token});
  if(error)throw error;const row=data as ConfirmationRow|undefined;if(!row)notFound();
  const rooms=row.items.filter(item=>item.type==='room'),experiences=row.items.filter(item=>item.type==='experience'),transfers=row.items.filter(item=>item.type==='transfer');
  const hasStay=Boolean(rooms.length&&row.checkIn&&row.checkOut),confirmed=row.status==='confirmed';
  const nights=hasStay?Math.round((new Date(`${row.checkOut}T00:00:00Z`).getTime()-new Date(`${row.checkIn}T00:00:00Z`).getTime())/86400000):0;
  const heading=hasStay?(experiences.length||transfers.length?'Your Borealis package is confirmed.':'Your stay is confirmed.'):'Your experience is confirmed.';
  const party=row.totalGuests===null?`${row.adults+row.children} guest${row.adults+row.children===1?'':'s'}`:occupancyLabel({adults:row.adults,children:row.children,infants:row.infants||0});
  return <PublicShell mobileBooking={false}><main className="bg-[#fbfaf7] py-12 md:py-20"><section className="shell"><div className="mx-auto max-w-3xl rounded-[2rem] bg-white p-7 shadow-sm md:p-12">
    <span className="grid size-16 place-items-center rounded-full bg-green text-2xl text-white">✓</span><p className="eyebrow mt-7">{confirmed?'Booking confirmed':'Reservation received'}</p><h1 className="mt-3 font-serif text-5xl leading-none text-lake">{confirmed?heading:'Your request is with Borealis.'}</h1><p className="mt-5 leading-7 text-muted">Keep this page or your booking reference for your records. Refreshing it will never create another reservation.</p>
    <div className="mt-8 rounded-2xl bg-ivory p-6"><p className="text-xs font-bold uppercase tracking-widest text-muted">Booking reference</p><p className="mt-2 font-serif text-4xl text-lake">{row.reference}</p><dl className="mt-7 grid gap-5 border-t border-lake/10 pt-6 sm:grid-cols-2"><Fact label="Guest" value={row.guestName}/>{hasStay&&<><Fact label="Rooms" value={`${rooms.length} room${rooms.length===1?'':'s'}`}/><Fact label="Check-in" value={row.checkIn||''}/><Fact label="Check-out" value={row.checkOut||''}/><Fact label="Stay" value={`${nights} night${nights===1?'':'s'}`}/><Fact label="Guests" value={party}/></>}<Fact label="Booking status" value={row.status.replaceAll('_',' ')}/><Fact label="Payment" value={`${row.paymentStatus.replaceAll('_',' ')}${row.paymentMethod==='pay_at_property'?' · pay at property':''}`}/></dl>
      {rooms.length>0&&<PackageItems title="Rooms" items={rooms} currency={row.currency}/>} {experiences.length>0&&<PackageItems title="Experiences" items={experiences} currency={row.currency}/>} {transfers.length>0&&<PackageItems title="Transportation" items={transfers} currency={row.currency}/>}<div className="mt-6 space-y-2 border-t border-lake/10 pt-6 text-sm">{hasStay&&<Price label="Stay" value={Number(row.roomSubtotal)} currency={row.currency}/>}<Price label={hasStay?'Add-ons':'Experience subtotal'} value={Number(row.addonsSubtotal)} currency={row.currency}/><Price label="Taxes and fees" value={Number(row.taxes)} currency={row.currency}/>{Number(row.discount)>0&&<Price label="Discount" value={-Number(row.discount)} currency={row.currency}/>}</div><div className="mt-6 flex items-end justify-between border-t border-lake/10 pt-6"><span className="text-sm text-muted">Total</span><strong className="font-serif text-4xl text-lake">{formatMoney(Number(row.total),row.currency)}</strong></div>
    </div><Link href="/" className="mt-8 inline-flex min-h-14 items-center justify-center rounded-full bg-lake px-8 text-sm font-bold text-white">Return home</Link>
  </div></section></main></PublicShell>;
}
function Fact({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-widest text-muted">{label}</dt><dd className="mt-1 font-semibold capitalize text-lake">{value}</dd></div>}
function PackageItems({title,items,currency}:{title:string;items:ConfirmationItem[];currency:string}){return <section className="mt-6 border-t border-lake/10 pt-6"><h2 className="text-xs font-bold uppercase tracking-widest text-muted">{title}</h2><div className="mt-3 space-y-3">{items.map((item,index)=><div key={`${item.type}:${index}`} className="flex justify-between gap-4"><div><p className="font-semibold text-lake">{item.title}</p><p className="mt-1 text-xs text-muted">{item.type==='room'?`${item.metadata?.occupancy?occupancyLabel(item.metadata.occupancy):`${item.metadata?.guestCount||''} guest(s)`}${item.metadata?.capacity?` · capacity ${item.metadata.capacity}`:''}`:<>{item.date}{item.time?` · ${String(item.time).slice(0,5)}`:''} · {item.metadata?.requestedQuantity||item.quantity} {item.type==='experience'?'participant(s)':'passenger(s)'}</>}</p></div><strong>{formatMoney(Number(item.subtotal),currency)}</strong></div>)}</div></section>}
function Price({label,value,currency}:{label:string;value:number;currency:string}){return <div className="flex justify-between"><span className="text-muted">{label}</span><span>{formatMoney(value,currency)}</span></div>}
