import type { Metadata } from 'next';
import Link from 'next/link';
import { ContactForm } from '@/components/public/ContactForm';
import { MapPlaceholder } from '@/components/public/MapPlaceholder';
import { PageHero, PublicShell } from '@/components/public/PageShell';
import { contact } from '@/data/public-content';
import { createMetadata } from '@/lib/seo';
export const metadata:Metadata=createMetadata({title:'Contact Borealis',description:'Contact Borealis Guest House about rooms, transfers, experiences and directions to Koman.'},'/contact');
export default function ContactPage(){return <PublicShell><PageHero eyebrow="Contact Borealis" title="Let us help with the journey." copy="Ask about a room, an experience, a transfer or the best way to reach us in Koman."/><section className="shell pb-20"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><aside className="rounded-[1.75rem] bg-lake p-7 text-white md:p-9"><h2 className="font-serif text-4xl">Talk to us directly.</h2><p className="mt-4 text-sm leading-6 text-white/60">Contact details are supplied from one central content record and can be replaced through the future CMS.</p><div className="mt-8 grid gap-3"><ContactAction label="Call" value={contact.phoneLabel} href={contact.phone?`tel:${contact.phone}`:undefined}/><ContactAction label="WhatsApp" value={contact.whatsappLabel} href={contact.whatsapp||undefined}/><ContactAction label="Email" value={contact.email} href={`mailto:${contact.email}`}/><ContactAction label="Instagram" value={contact.instagramLabel} href={contact.instagram||undefined}/></div><div className="mt-8 border-t border-white/15 pt-7"><p className="text-xs font-bold uppercase tracking-widest text-sand">Address</p><p className="mt-3 text-sm leading-6 text-white/70">{contact.address}</p></div>{contact.placeholder&&<p className="mt-6 text-xs leading-5 text-white/45">Preview contact data. Phone, WhatsApp, Instagram and the full address must be confirmed before launch.</p>}</aside><div><ContactForm/></div></div></section><section className="bg-ivory py-20 md:py-24"><div className="shell grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">How to reach Borealis</p><h2 className="mt-4 font-serif text-5xl text-lake md:text-6xl">Plan the final part of your journey.</h2><p className="mt-6 max-w-lg leading-8 text-muted">Koman connections can vary by route and season. Contact us for current directions, or explore the transfer services being prepared for guests.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/transfers" className="min-h-14 rounded-full bg-lake px-7 py-4 text-center text-sm font-bold text-white">View transfers</Link><Link href="/book" className="min-h-14 rounded-full bg-sand px-7 py-4 text-center text-sm font-bold text-lake">Check availability</Link></div></div><MapPlaceholder contact={contact}/></div></section></PublicShell>}
function ContactAction({label,value,href}:{label:string;value:string;href?:string}){const content=<><span><span className="block text-xs font-bold uppercase tracking-widest text-sand">{label}</span><span className="mt-1 block text-sm text-white/75">{value}</span></span><span aria-hidden="true" className="text-xl">{href?'→':'—'}</span></>;return href?<Link href={href} className="flex min-h-16 items-center justify-between rounded-xl bg-white/8 px-5">{content}</Link>:<div className="flex min-h-16 items-center justify-between rounded-xl bg-white/5 px-5">{content}</div>}
