'use client';
import { useActionState } from 'react';
import { saveExternalCalendar } from '@/app/admin/channels/actions';
import type { CalendarProvider,ChannelActionState,ExternalCalendarAdmin } from '@/types/channels-admin';
const initial:ChannelActionState={ok:false,message:''};
const field='mt-2 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm';
export function ExternalCalendarForm({calendar,rooms,roomTypes,fixedProvider}:{calendar?:ExternalCalendarAdmin;rooms:{id:string;name:string}[];roomTypes:{id:string;name:string}[];fixedProvider?:CalendarProvider}){
  const[state,action,pending]=useActionState(saveExternalCalendar,initial),provider=fixedProvider||calendar?.provider||'booking_com';
  const target=calendar?.roomId?`room:${calendar.roomId}`:calendar?.roomTypeId?`type:${calendar.roomTypeId}`:'';
  return <form action={action} className="grid gap-4"><input type="hidden" name="id" value={calendar?.id||''}/>{fixedProvider&&<input type="hidden" name="provider" value={fixedProvider}/>}<label className="text-sm font-semibold">Connection name<input name="name" required maxLength={120} defaultValue={calendar?.name||''} placeholder="Booking.com — Lake room" className={field}/>{state.errors?.name&&<span className="mt-1 block text-xs text-red-700">{state.errors.name}</span>}</label>{!fixedProvider&&<label className="text-sm font-semibold">Provider<select name="provider" defaultValue={provider} className={field}><option value="booking_com">Booking.com</option><option value="airbnb">Airbnb</option><option value="other">Other</option></select></label>}<label className="text-sm font-semibold">Room inventory<select name="target" required defaultValue={target} className={field}><option value="">Choose a room or room type</option>{rooms.length>0&&<optgroup label="Physical rooms">{rooms.map(room=><option key={room.id} value={`room:${room.id}`}>{room.name}</option>)}</optgroup>}{roomTypes.length>0&&<optgroup label="Room types (blocks the full type)">{roomTypes.map(room=><option key={room.id} value={`type:${room.id}`}>{room.name}</option>)}</optgroup>}</select>{state.errors?.target&&<span className="mt-1 block text-xs text-red-700">{state.errors.target}</span>}</label><label className="text-sm font-semibold">Direction<select name="direction" defaultValue={calendar?.direction||'import'} className={field}><option value="import">Import into Borealis</option><option value="export">Export from Borealis</option><option value="both">Import and export</option></select></label><label className="text-sm font-semibold">Private iCal import URL<input name="calendarUrl" type="password" inputMode="url" autoComplete="new-password" placeholder={calendar?.importHost!==undefined?`Saved securely (${calendar.importHost}) — leave blank to keep`:'https://…'} className={field}/><span className="mt-1 block text-xs font-normal text-slate-500">Required for import. The saved token is never rendered back into the page.</span>{state.errors?.calendarUrl&&<span className="mt-1 block text-xs text-red-700">{state.errors.calendarUrl}</span>}</label><label className="flex min-h-11 items-center gap-2 text-sm font-semibold"><input name="enabled" type="checkbox" defaultChecked={calendar?.enabled??true}/>Synchronization enabled</label>{state.message&&<p role="status" className={`rounded-lg px-3 py-2 text-sm ${state.ok?'bg-emerald-50 text-emerald-800':'bg-red-50 text-red-800'}`}>{state.message}</p>}<button disabled={pending||(!rooms.length&&!roomTypes.length)} className="inline-flex min-h-11 items-center justify-center rounded-lg bg-[#164b59] px-4 text-center text-sm font-bold text-white disabled:opacity-50">{pending?'Saving…':calendar?'Update connection':'Add calendar'}</button></form>
}

