import Link from'next/link';
import{AdminPageHeader}from'@/components/admin/ui';
import{SeoSettingsForm}from'@/components/admin/SeoSettingsForm';
import{PageSeoForm}from'@/components/admin/PageSeoForm';
import{requireAdmin}from'@/lib/admin/auth';
import{adminSeoRepository}from'@/lib/repositories/admin/seo';
export default async function SeoPage(){const s=await requireAdmin(['owner','manager','editor']),[data,pageRecords]=await Promise.all([adminSeoRepository.dashboard(s),adminSeoRepository.pageRecords(s)]);return <div className="space-y-10"><AdminPageHeader title="SEO" description="Manage global defaults and every primary public route from one place."/><SeoSettingsForm settings={data.settings} media={data.media}/><section className="space-y-4"><div><h2 className="text-xl font-bold">Primary page SEO</h2><p className="mt-1 text-sm text-slate-500">Titles, descriptions, social sharing, canonicals, slugs and indexing are CMS-controlled.</p></div>{pageRecords.map(page=><PageSeoForm key={page.id} page={page} media={data.media}/>)}</section><section className="space-y-4"><div><h2 className="text-xl font-bold">Detail-page audit</h2><p className="mt-1 text-sm text-slate-500">Rooms, experiences, transfers and articles inherit property defaults when their own SEO fields are empty.</p></div><SeoMobileList rows={data.pages}/><div className="hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white md:block"><table className="min-w-[850px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Page</th><th className="p-4">SEO title</th><th className="p-4">Meta description</th><th className="p-4">Index</th><th className="p-4"></th></tr></thead><tbody>{data.pages.map(row=><tr key={`${row.id}-${row.url}`} className="border-t border-slate-100 align-top"><td className="p-4"><strong className="block">{row.page}</strong><span className="text-xs text-slate-500">{row.url}</span></td><td className="max-w-52 p-4">{row.title||'Uses fallback'}</td><td className="max-w-80 p-4 text-slate-600">{row.description||'Uses fallback'}</td><td className="p-4">{row.indexed?'Index':'Noindex'}</td><td className="p-4"><Link href={row.editHref} className="inline-flex min-h-11 items-center font-bold underline">Edit</Link></td></tr>)}</tbody></table></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Image alt-text audit</h2>{data.missingAlt.length?<><p className="mt-2 text-sm text-amber-700">{data.missingAlt.length} active image{data.missingAlt.length===1?' is':'s are'} missing alternative text.</p><Link href="/admin/media" className="mt-4 inline-flex min-h-11 items-center font-bold underline">Review media</Link></>:<p className="mt-2 text-sm text-emerald-700">All active media records have alternative text.</p>}</section><section className="rounded-2xl border border-dashed border-slate-300 p-6"><h2 className="font-bold">Slug and redirect readiness</h2><p className="mt-2 text-sm leading-6 text-slate-600">Published slug changes require confirmation. Each change stores an inactive 301 redirect candidate for later review and activation.</p></section></div>}

type SeoRow=Awaited<ReturnType<typeof adminSeoRepository.dashboard>>['pages'][number];
function SeoMobileList({rows}:{rows:SeoRow[]}){return <div className="grid gap-3 md:hidden">{rows.map(row=><article key={`${row.id}-${row.url}`} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-bold text-slate-950">{row.page}</h3><p className="truncate text-xs text-slate-500">{row.url}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-bold ${row.indexed?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-800'}`}>{row.indexed?'Index':'Noindex'}</span></div><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs font-bold uppercase text-slate-500">SEO title</dt><dd className="mt-1 break-words">{row.title||'Uses fallback'}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-500">Description</dt><dd className="mt-1 text-slate-600">{row.description||'Uses fallback'}</dd></div></dl><Link href={row.editHref} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-lg border border-slate-300 font-bold">Edit SEO</Link></article>)}</div>}
