export interface SEOData { title: string; description: string; canonical?: string; image?: string; ogTitle?:string; ogDescription?:string; noindex?:boolean }
export interface Amenity { id: string; name: string; icon?: string }
export interface Property { name: string; tagline: string; description: string; location: string; heroImage: string; amenities: Amenity[]; seo: SEOData }
export interface RoomType { id: string; name: string; description: string; capacity: number }
export interface Room { id: string; slug: string; name: string; eyebrow: string; description: string; longDescription: string; image: string; gallery: string[]; priceFrom: number|null; currency:string; capacity: number; beds: string; size: string; viewType: string; amenities: Amenity[]; seo: SEOData }
export interface Experience { id: string; slug: string; title: string; description: string; longDescription: string; image: string; gallery: string[]; duration: string; capacity: string; maxCapacity?:number|null; minimumQuantity?:number; maximumQuantity?:number|null; priceFrom: number | null; currency:string; priceType: string; availability: string; meetingPoint: string; included: string[]; notes: string[]; bookingRequirements: string[]; category: string; featured:boolean; bookable:boolean; bookIndependently?:boolean; seo: SEOData }
export interface TransferRoute { id:string; slug:string; origin:string; destination:string; description:string; fullDescription:string; duration:string; capacity:number|null; vehicleServiceType:string; pricingMethod:'fixed'|'from'|'quote'|'fixed_vehicle'|'per_passenger'|'on_request'; currency:string; price:number|null; bookingNotice:string; active:boolean; featured:boolean; bookable:boolean; availabilityMode:'always'|'scheduled'|'on_request'; availableDays:number[]; windowStart:string; windowEnd:string; image:string; gallery:string[]; seo:SEOData }
export interface TourismCategory { id: string; name: string; slug: string }
export interface TourismArticle { id:string; slug:string; title:string; subtitle?:string; excerpt:string; body:string[]; blocks?:import('./explore-admin').ArticleBlock[]; image:string; gallery?:{id:string;url:string;alt:string}[]; featuredGallery?:{id:string;url:string;alt:string}[]; category:TourismCategory; readTime:string; author?:string; publishedAt?:string; featured?:boolean; related?:Record<string,{label:string;href:string}>; relatedArticleIds?:string[]; relatedExperienceIds?:string[]; relatedTransferIds?:string[]; seo:SEOData&{ogImage?:string;canonical?:string;noindex?:boolean} }
export interface GalleryItem { id: string; src: string; alt: string; category: string }
export interface Review { id: string; quote: string; author: string; origin: string }
export interface ContactInfo { email: string; phone: string; phoneLabel: string; whatsapp: string; whatsappLabel: string; instagram: string; instagramLabel: string; address: string; mapsUrl: string; placeholder: boolean }
export interface AboutSection { id: string; eyebrow: string; title: string; copy: string; image: string; imageAlt: string }
export interface AboutContent { heroEyebrow:string; heroTitle: string; heroCopy: string; heroImage: string; heroImageAlt:string; sections: AboutSection[]; philosophyEyebrow:string; philosophyHeading:string; philosophy: string[] }
