import 'server-only';
import {createServerSupabaseClient} from '@/lib/supabase/server';import type {AdminSession} from '@/lib/admin/auth';import type {AdminAmenityRecord,AmenityInput} from '@/types/amenities-admin';
export const adminAmenitiesRepository={
async list(session:AdminSession):Promise<AdminAmenityRecord[]>{const db=await createServerSupabaseClient();const[{data,error},{data:typeLinks},{data:roomLinks}]=await Promise.all([db.from('amenities').select('id,name,icon,category,description,active,sort_order,status').eq('property_id',session.propertyId).order('sort_order').order('name'),db.from('room_type_amenities').select('amenity_id').eq('property_id',session.propertyId),db.from('room_amenities').select('amenity_id,rooms!inner(property_id)').eq('rooms.property_id',session.propertyId)]);if(error)throw error;const count=(links:{amenity_id:string}[]|null|undefined,id:string)=>links?.filter(item=>item.amenity_id===id).length||0;return(data||[]).map(row=>({id:row.id,name:row.name,icon:row.icon||'',category:row.category,description:row.description||'',active:row.active,sortOrder:row.sort_order,status:row.status,roomTypeUsage:count(typeLinks,row.id),physicalRoomUsage:count(roomLinks as {amenity_id:string}[]|null,row.id)}))},
async get(session:AdminSession,id:string){return(await this.list(session)).find(item=>item.id===id)||null},
async save(session:AdminSession,id:string|null,input:AmenityInput){const db=await createServerSupabaseClient();const values={property_id:session.propertyId,name:input.name,icon:input.icon||null,category:input.category,description:input.description||null,active:input.active,is_visible:input.active,status:input.status,sort_order:input.sortOrder,updated_by:session.userId,archived_at:null};const result=id?await db.from('amenities').update(values).eq('id',id).eq('property_id',session.propertyId).select('id').single():await db.from('amenities').insert({...values,created_by:session.userId}).select('id').single();if(result.error)throw result.error;return result.data.id},
async setStatus(session:AdminSession,id:string,status:'archived'|'draft'){const db=await createServerSupabaseClient();const{error}=await db.from('amenities').update({status,active:status!=='archived',is_visible:status!=='archived',archived_at:status==='archived'?new Date().toISOString():null,updated_by:session.userId}).eq('id',id).eq('property_id',session.propertyId);if(error)throw error},
async reorder(session:AdminSession,id:string,direction:'up'|'down'){const db=await createServerSupabaseClient();const{data,error}=await db.from('amenities').select('id,sort_order').eq('property_id',session.propertyId).neq('status','archived').order('sort_order').order('name');if(error)throw error;const ordered=data||[],index=ordered.findIndex(item=>item.id===id),target=direction==='up'?index-1:index+1;if(index<0||target<0||target>=ordered.length)return;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];for(const[position,item]of ordered.entries()){const result=await db.from('amenities').update({sort_order:position*10,updated_by:session.userId}).eq('id',item.id).eq('property_id',session.propertyId);if(result.error)throw result.error}}
};
