import'server-only';
import{createServerSupabaseClient}from'@/lib/supabase/server';
import type{AdminSession}from'@/lib/admin/auth';
import type{BookingDetail,BookingListRow,ManagedBookingStatus,ManagedPaymentStatus,ManualBookingRoom}from'@/types/bookings-admin';

const transitions:Record<ManagedBookingStatus,ManagedBookingStatus[]>={held:['pending','cancelled'],pending:['awaiting_payment','confirmed','cancelled'],awaiting_payment:['confirmed','cancelled'],confirmed:['checked_in','cancelled'],checked_in:['completed'],completed:[],cancelled:[]};
type Guest={first_name:string;last_name:string;email:string|null;phone:string|null;country:string|null;is_primary:boolean};
type Item={id:string;item_type:string;title_snapshot:string|null;quantity:number;unit_price:number|string;total_price:number|string;service_date?:string|null;service_time?:string|null;item_status?:string|null;metadata?:{requestedQuantity?:number;guestCount?:number;capacity?:number;occupancy?:{adults:number;children:number;infants:number}}|null};
function guestOf(row:{booking_guests?:Guest[]}){return(row.booking_guests||[]).find(x=>x.is_primary)||row.booking_guests?.[0]}

export const adminBookingsRepository={
 async list(s:AdminSession,filters:{query?:string;status?:string;from?:string;to?:string;roomTypeId?:string;period?:string}):Promise<BookingListRow[]>{
  const db=await createServerSupabaseClient();let query=db.from('bookings').select('id,reference,booking_status,payment_status,source,check_in,check_out,adults,children,infants,total_guests,total_amount,currency,created_at,booking_guests(first_name,last_name,email,is_primary),booking_items(item_type,title_snapshot,room_type_id,service_date,service_time,quantity,metadata)').eq('property_id',s.propertyId).order('created_at',{ascending:false});
  const today=new Date().toISOString().slice(0,10);if(filters.status)query=query.eq('booking_status',filters.status);else if(filters.period==='cancelled')query=query.eq('booking_status','cancelled');else query=query.neq('booking_status','cancelled');
  const{data,error}=await query;if(error)throw error;const needle=filters.query?.toLowerCase();
  return(data||[]).map(row=>{const guest=guestOf(row as unknown as{booking_guests:Guest[]}),items=row.booking_items as unknown as(Item&{room_type_id:string|null})[],roomItems=items.filter(x=>x.item_type==='room'),roomItem=roomItems[0],primary=roomItem||items[0];return{id:row.id,reference:row.reference||row.id.slice(0,8).toUpperCase(),status:row.booking_status as ManagedBookingStatus,paymentStatus:row.payment_status as ManagedPaymentStatus,source:row.source||'direct',checkIn:row.check_in,checkOut:row.check_out,serviceDate:primary?.service_date||null,serviceTime:(primary?.service_time||'').slice(0,5)||null,bookingType:roomItem?(items.length>1?'Package':'Room'):(primary?.item_type==='experience'?'Experience':primary?.item_type||'Booking'),quantity:roomItem?roomItems.length:Number(primary?.metadata?.requestedQuantity||primary?.quantity||0),adults:Number(row.adults||0),children:Number(row.children||0),infants:row.infants==null?null:Number(row.infants),totalGuests:row.total_guests==null?null:Number(row.total_guests),guestName:guest?`${guest.first_name} ${guest.last_name}`:'Guest',email:guest?.email||'',room:roomItem?roomItems.map(item=>item.title_snapshot||'Room').join(' + '):primary?.title_snapshot||'Booking',total:Number(row.total_amount||0),currency:row.currency||'EUR',createdAt:row.created_at,roomTypeIds:roomItems.map(item=>item.room_type_id).filter(Boolean)}}).filter(x=>{const start=x.checkIn||x.serviceDate,end=x.checkOut||x.serviceDate;return(!needle||[x.reference,x.guestName,x.email,x.room].some(value=>value.toLowerCase().includes(needle)))&&(!filters.roomTypeId||x.roomTypeIds.includes(filters.roomTypeId))&&(!filters.from||Boolean(start&&start>=filters.from))&&(!filters.to||Boolean(end&&end<=filters.to))&&(filters.period!=='upcoming'||Boolean(start&&start>=today))&&(filters.period!=='current'||Boolean(start&&end&&start<=today&&end>=today))&&(filters.period!=='past'||Boolean(end&&end<today))}).map(x=>{const row={...x};delete(row as{roomTypeIds?:Array<string|null>}).roomTypeIds;return row})},
 async get(s:AdminSession,id:string):Promise<BookingDetail|null>{
  const db=await createServerSupabaseClient(),{data,error}=await db.from('bookings').select('id,reference,booking_status,payment_status,payment_method,source,check_in,check_out,total_amount,subtotal,room_subtotal,addons_subtotal,taxes_fees,discount_amount,currency,created_at,adults,children,infants,total_guests,notes,internal_note,hold_expires_at,booking_guests(first_name,last_name,email,phone,country,is_primary),booking_items(id,item_type,title_snapshot,quantity,unit_price,total_price,service_date,service_time,item_status,metadata)').eq('property_id',s.propertyId).eq('id',id).maybeSingle();if(error)throw error;if(!data)return null;
  const guest=guestOf(data as unknown as{booking_guests:Guest[]}),items=data.booking_items as unknown as Item[],roomItems=items.filter(x=>x.item_type==='room'),room=roomItems[0];
  const primary=room||items[0],infants=data.infants==null?null:Number(data.infants),totalGuests=data.total_guests==null?null:Number(data.total_guests);return{id:data.id,reference:data.reference||data.id.slice(0,8).toUpperCase(),status:data.booking_status as ManagedBookingStatus,paymentStatus:data.payment_status as ManagedPaymentStatus,paymentMethod:data.payment_method||'',source:data.source||'direct',checkIn:data.check_in,checkOut:data.check_out,serviceDate:primary?.service_date||null,serviceTime:(primary?.service_time||'').slice(0,5)||null,bookingType:room?(items.length>1?'Package':'Room'):(primary?.item_type==='experience'?'Experience':primary?.item_type||'Booking'),quantity:room?roomItems.length:Number(primary?.metadata?.requestedQuantity||primary?.quantity||0),adults:Number(data.adults||0),children:Number(data.children||0),infants,totalGuests,guestName:guest?`${guest.first_name} ${guest.last_name}`:'Guest',email:guest?.email||'',phone:guest?.phone||'',country:guest?.country||'',room:room?roomItems.map(item=>item.title_snapshot||'Room').join(' + '):primary?.title_snapshot||'Booking',total:Number(data.total_amount||0),roomSubtotal:Number(data.room_subtotal||room?.total_price||0),addonsSubtotal:Number(data.addons_subtotal||(!room?data.subtotal:0)||0),taxes:Number(data.taxes_fees||0),discount:Number(data.discount_amount||0),currency:data.currency||'EUR',createdAt:data.created_at,guestCount:totalGuests??Number(data.adults||0)+Number(data.children||0),notes:data.notes||'',internalNote:data.internal_note||'',holdExpiresAt:data.hold_expires_at||'',items:items.map(x=>({id:x.id,type:x.item_type,title:x.title_snapshot||x.item_type,quantity:x.quantity,unitPrice:Number(x.unit_price),totalPrice:Number(x.total_price),serviceDate:x.service_date||'',serviceTime:(x.service_time||'').slice(0,5),status:x.item_status||data.booking_status,requestedQuantity:Number(x.metadata?.requestedQuantity||x.quantity),guestCount:x.metadata?.guestCount??null,capacity:x.metadata?.capacity??null,occupancy:x.metadata?.occupancy??null}))}},
 async rooms(s:AdminSession):Promise<ManualBookingRoom[]>{const db=await createServerSupabaseClient(),{data,error}=await db.from('room_types').select('id,name,capacity').eq('property_id',s.propertyId).eq('status','published').eq('is_visible',true).order('name');if(error)throw error;return(data||[]).map(x=>({id:x.id,name:x.name,capacity:Number(x.capacity)}))},
 async createManual(s:AdminSession,input:{roomTypeId:string;checkIn:string;checkOut:string;adults:number;children:number;infants:number;firstName:string;lastName:string;email:string;phone:string;country:string;notes:string}){const db=await createServerSupabaseClient(),{data,error}=await db.rpc('create_admin_booking',{target_room_type:input.roomTypeId,stay_start:input.checkIn,stay_end:input.checkOut,adult_count:input.adults,child_count:input.children,infant_count:input.infants,guest_data:{firstName:input.firstName,lastName:input.lastName,email:input.email,phone:input.phone,country:input.country,notes:input.notes}});if(error)throw error;const result=Array.isArray(data)?data[0]:data;if(!result)throw new Error('The manual booking could not be created.');return{id:result.booking_id as string,reference:result.reference as string}},
 async updateStatus(s:AdminSession,id:string,next:ManagedBookingStatus){const db=await createServerSupabaseClient(),current=await this.get(s,id);if(!current)throw new Error('Booking not found.');if(!transitions[current.status].includes(next))throw new Error(`A ${current.status.replaceAll('_',' ')} booking cannot move to ${next.replaceAll('_',' ')}.`);const{data,error}=await db.from('bookings').update({booking_status:next,status:next,hold_expires_at:null,updated_by:s.userId,updated_at:new Date().toISOString()}).eq('property_id',s.propertyId).eq('id',id).eq('booking_status',current.status).select('id');if(error)throw error;if(!data?.length)throw new Error('The booking changed before this update. Refresh and try again.')},
 async saveNote(s:AdminSession,id:string,note:string){const db=await createServerSupabaseClient(),{error}=await db.from('bookings').update({internal_note:note||null,updated_by:s.userId,updated_at:new Date().toISOString()}).eq('property_id',s.propertyId).eq('id',id);if(error)throw error},allowed(status:ManagedBookingStatus){return transitions[status]}
};
