import 'server-only';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import type { AdminSession } from '@/lib/admin/auth';
import type { CmsPage, CmsPageContent, ContentStatus } from '@/types/admin';

interface PageRow { id:string;property_id:string;slug:string;title:string;content:string|null;status:ContentStatus;seo_title:string|null;seo_description:string|null;updated_at:string }
function mapPage(row:PageRow):CmsPage{let content:CmsPageContent={heroHeading:'',heroCopy:'',eyebrow:''};try{content={...content,...JSON.parse(row.content||'{}')}}catch{}return{id:row.id,propertyId:row.property_id,slug:row.slug,title:row.title,content,status:row.status,seoTitle:row.seo_title||'',seoDescription:row.seo_description||'',updatedAt:row.updated_at}}

export const cmsPageRepository={
  async list(session:AdminSession):Promise<CmsPage[]>{const supabase=await createServerSupabaseClient();const{data,error}=await supabase.from('pages').select('id,property_id,slug,title,content,status,seo_title,seo_description,updated_at').eq('property_id',session.propertyId).order('slug');if(error)throw error;return(data as PageRow[]).map(mapPage)},
  async getBySlug(session:AdminSession,slug:string):Promise<CmsPage|null>{const supabase=await createServerSupabaseClient();const{data,error}=await supabase.from('pages').select('id,property_id,slug,title,content,status,seo_title,seo_description,updated_at').eq('property_id',session.propertyId).eq('slug',slug).maybeSingle();if(error)throw error;return data?mapPage(data as PageRow):null},
  async save(session:AdminSession,slug:string,input:{title:string;content:CmsPageContent;status:ContentStatus;seoTitle:string;seoDescription:string}){const supabase=await createServerSupabaseClient();const existing=await this.getBySlug(session,slug);const values={property_id:session.propertyId,slug,title:input.title,content:JSON.stringify(input.content),status:input.status,is_published:input.status==='published',seo_title:input.seoTitle||null,seo_description:input.seoDescription||null,updated_by:session.userId,updated_at:new Date().toISOString(),published_at:input.status==='published'?new Date().toISOString():null,archived_at:null};const query=existing?supabase.from('pages').update(values).eq('id',existing.id):supabase.from('pages').insert({...values,created_by:session.userId});const{data,error}=await query.select('id').single();if(error)throw error;await supabase.from('audit_logs').insert({property_id:session.propertyId,actor_id:session.userId,action:existing?'updated':'created',entity_type:'page',entity_id:data.id,metadata:{slug,status:input.status}});return data.id},
  async archive(session:AdminSession,slug:string){const supabase=await createServerSupabaseClient();const existing=await this.getBySlug(session,slug);if(!existing)return;const{error}=await supabase.from('pages').update({status:'archived',is_published:false,archived_at:new Date().toISOString(),updated_at:new Date().toISOString(),updated_by:session.userId}).eq('id',existing.id);if(error)throw error;await supabase.from('audit_logs').insert({property_id:session.propertyId,actor_id:session.userId,action:'archived',entity_type:'page',entity_id:existing.id,metadata:{slug}})},
};
