import 'server-only';
import{createServerSupabaseClient}from'@/lib/supabase/server';
import type{AdminSession}from'@/lib/admin/auth';
import type{AdminArticle,ArticleBlock,ArticleEditorData,EditorialOption,ExploreCategory}from'@/types/explore-admin';
import type{validateArticle}from'@/lib/admin/explore-validation';
import{slugFrom}from'@/lib/slugs';
type Input=NonNullable<ReturnType<typeof validateArticle>['data']>;
const mediaUrl=(base:string,path:string)=>`${base}/storage/v1/object/public/public-media/${path}`;
const unique=(ids:(string|null|undefined)[])=>Array.from(new Set(ids.filter(Boolean)))as string[];

async function assertReferences(db:Awaited<ReturnType<typeof createServerSupabaseClient>>,s:AdminSession,id:string|null,input:Input){
  const blocks=input.blocks as ArticleBlock[],blockMedia=blocks.flatMap(block=>[block.mediaId,...(block.mediaIds||[])]),blockExperiences=blocks.filter(x=>x.type==='related_experience').map(x=>x.relatedId),blockTransfers=blocks.filter(x=>x.type==='related_transfer').map(x=>x.relatedId),blockRooms=blocks.filter(x=>x.type==='related_room').map(x=>x.relatedId);
  const checks:[string,string[],string][]=[['tourism_categories',unique([input.categoryId]),'category'],['media_assets',unique([input.heroMediaId,input.ogMediaId,...input.galleryMediaIds,...blockMedia]),'media'],['tourism_articles',unique(input.relatedArticleIds.filter(x=>x!==id)),'related article'],['experiences',unique([...input.relatedExperienceIds,...blockExperiences]),'related experience'],['transfer_routes',unique([...input.relatedTransferIds,...blockTransfers]),'related transfer'],['room_types',unique(blockRooms),'related room']];
  for(const[table,ids,label]of checks){if(!ids.length)continue;const{data,error}=await db.from(table).select('id').eq('property_id',s.propertyId).in('id',ids).neq('status','archived');if(error)throw error;if((data||[]).length!==ids.length)throw new Error(`Select a valid ${label} from this property.`)}
}

export const adminExploreRepository={
  async categories(s:AdminSession):Promise<ExploreCategory[]>{const db=await createServerSupabaseClient();const{data,error}=await db.from('tourism_categories').select('id,title,slug,description,status,sort_order').eq('property_id',s.propertyId).order('sort_order');if(error)throw error;return(data||[]).map(x=>({id:x.id,title:x.title,slug:x.slug,description:x.description||'',status:x.status,sortOrder:x.sort_order}))},
  async list(s:AdminSession):Promise<AdminArticle[]>{
    const db=await createServerSupabaseClient(),base=process.env.NEXT_PUBLIC_SUPABASE_URL||'';
    const[{data,error},{data:media},{data:seo}]=await Promise.all([db.from('tourism_articles').select('id,title,slug,subtitle,excerpt,category_id,hero_media_id,gallery_media_ids,status,is_featured,published_at,author_name,sort_order,content_blocks,related_article_ids,related_experience_ids,related_transfer_ids,updated_at').eq('property_id',s.propertyId).order('sort_order'),db.from('media_assets').select('id,file_path').eq('property_id',s.propertyId),db.from('seo_metadata').select('entity_id,title,meta_description,og_image_id,canonical_override,noindex').eq('property_id',s.propertyId).eq('entity_type','tourism_article')]);
    if(error)throw error;const paths=new Map((media||[]).map(x=>[x.id,x.file_path]));
    return(data||[]).map(x=>{const meta=(seo||[]).find(m=>m.entity_id===x.id),path=paths.get(x.hero_media_id||'');return{id:x.id,title:x.title,slug:x.slug,subtitle:x.subtitle||'',excerpt:x.excerpt||'',categoryId:x.category_id||'',heroMediaId:x.hero_media_id||'',imageUrl:path?mediaUrl(base,path):'',galleryMediaIds:x.gallery_media_ids||[],status:x.status,featured:x.is_featured,publishDate:x.published_at?String(x.published_at).slice(0,16):'',author:x.author_name||'',sortOrder:x.sort_order,blocks:x.content_blocks||[],relatedArticleIds:x.related_article_ids||[],relatedExperienceIds:x.related_experience_ids||[],relatedTransferIds:x.related_transfer_ids||[],seoTitle:meta?.title||'',seoDescription:meta?.meta_description||'',ogMediaId:meta?.og_image_id||'',canonicalOverride:meta?.canonical_override||'',noindex:meta?.noindex||false,updatedAt:x.updated_at}})
  },
  async get(s:AdminSession,id:string){return(await this.list(s)).find(x=>x.id===id)||null},
  async editor(s:AdminSession,currentId?:string):Promise<ArticleEditorData>{
    const db=await createServerSupabaseClient(),base=process.env.NEXT_PUBLIC_SUPABASE_URL||'';
    const[categories,media,articles,experiences,transfers,rooms]=await Promise.all([this.categories(s),db.from('media_assets').select('id,filename,alt_text,file_path').eq('property_id',s.propertyId).neq('status','archived').order('sort_order'),db.from('tourism_articles').select('id,title').eq('property_id',s.propertyId).neq('status','archived'),db.from('experiences').select('id,name').eq('property_id',s.propertyId).neq('status','archived'),db.from('transfer_routes').select('id,origin,destination').eq('property_id',s.propertyId).neq('status','archived'),db.from('room_types').select('id,name').eq('property_id',s.propertyId).neq('status','archived')]);
    const opts=(rows:{id:string;label:string}[]):EditorialOption[]=>rows;
    return{categories,media:(media.data||[]).map(x=>({id:x.id,label:x.alt_text||x.filename,url:mediaUrl(base,x.file_path)})),articles:opts((articles.data||[]).filter(x=>x.id!==currentId).map(x=>({id:x.id,label:x.title}))),experiences:opts((experiences.data||[]).map(x=>({id:x.id,label:x.name}))),transfers:opts((transfers.data||[]).map(x=>({id:x.id,label:`${x.origin} → ${x.destination}`}))),rooms:opts((rooms.data||[]).map(x=>({id:x.id,label:x.name})))}}
  ,
  async save(s:AdminSession,id:string|null,input:Input){
    const db=await createServerSupabaseClient();await assertReferences(db,s,id,input);
    const values={property_id:s.propertyId,title:input.title,slug:input.slug,subtitle:input.subtitle,description:input.subtitle,excerpt:input.excerpt,category_id:input.categoryId,hero_media_id:input.heroMediaId,gallery_media_ids:input.galleryMediaIds,status:input.status,is_featured:input.featured,is_visible:input.status==='published',published_at:input.status==='published'?(input.publishDate||new Date().toISOString()):input.publishDate,author_name:input.author,sort_order:input.sortOrder,content_blocks:input.blocks,related_article_ids:input.relatedArticleIds,related_experience_ids:input.relatedExperienceIds,related_transfer_ids:input.relatedTransferIds,updated_by:s.userId,archived_at:null};
    const result=id?await db.from('tourism_articles').update(values).eq('id',id).eq('property_id',s.propertyId).select('id').single():await db.from('tourism_articles').insert({...values,created_by:s.userId}).select('id').single();if(result.error)throw result.error;const articleId=result.data.id;
    const{error}=await db.from('seo_metadata').upsert({property_id:s.propertyId,entity_type:'tourism_article',entity_id:articleId,title:input.seoTitle||input.title,meta_description:input.seoDescription||input.excerpt,og_image_id:input.ogMediaId||input.heroMediaId,canonical_override:input.canonicalOverride||null,noindex:input.noindex,nofollow:false,status:input.status,created_by:s.userId,updated_by:s.userId},{onConflict:'property_id,entity_type,entity_id'});if(error)throw error;return articleId
  },
  async status(s:AdminSession,id:string,status:'draft'|'archived'){const db=await createServerSupabaseClient(),archivedAt=status==='archived'?new Date().toISOString():null;const[article,seo]=await Promise.all([db.from('tourism_articles').update({status,is_visible:false,archived_at:archivedAt,updated_by:s.userId}).eq('id',id).eq('property_id',s.propertyId),db.from('seo_metadata').update({status,updated_by:s.userId}).eq('entity_type','tourism_article').eq('entity_id',id).eq('property_id',s.propertyId)]);if(article.error)throw article.error;if(seo.error)throw seo.error},
  async saveCategory(s:AdminSession,d:FormData){const db=await createServerSupabaseClient(),id=String(d.get('id')||''),title=String(d.get('title')||'').trim(),values={property_id:s.propertyId,title,slug:slugFrom(String(d.get('slug')||''),title),description:String(d.get('description')||'').trim(),sort_order:Number(d.get('sortOrder')||0),status:'published',is_visible:true,updated_by:s.userId,archived_at:null};if(!values.title||!values.slug)throw new Error('Enter a category title that can be used to generate its URL slug.');const result=id?await db.from('tourism_categories').update(values).eq('id',id).eq('property_id',s.propertyId):await db.from('tourism_categories').insert({...values,created_by:s.userId});if(result.error)throw result.error},
  async archiveCategory(s:AdminSession,id:string){const db=await createServerSupabaseClient();const{error}=await db.from('tourism_categories').update({status:'archived',is_visible:false,archived_at:new Date().toISOString(),updated_by:s.userId}).eq('id',id).eq('property_id',s.propertyId);if(error)throw error}
};
