import 'server-only';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import type {AdminSession} from '@/lib/admin/auth';
import {findSeasonalConflicts} from '@/lib/pricing/core';
import type {PricingRule,RateRoomType,SeasonalRate} from '@/types/rates-admin';
type PeriodRow={id:string;name:string;start_date:string;end_date:string;nightly_price:number;currency:string|null;active:boolean;status:'draft'|'published'|'archived'};
export const adminRatesRepository={
 async listRoomTypes(session:AdminSession):Promise<RateRoomType[]>{const db=await createServerSupabaseClient();const[{data:rooms,error},{data:rates},{data:property}]=await Promise.all([db.from('room_types').select('id,name').eq('property_id',session.propertyId).neq('status','archived').order('sort_order'),db.from('rates').select('room_type_id,base_price,currency,active,updated_at').eq('property_id',session.propertyId).neq('status','archived').order('updated_at',{ascending:false}),db.from('properties').select('currency').eq('id',session.propertyId).single()]);if(error)throw error;const fallbackCurrency=property?.currency||'EUR';return(rooms||[]).map(room=>{const rate=(rates||[]).find(item=>item.room_type_id===room.id);return{id:room.id,name:room.name,basePrice:rate?Number(rate.base_price):null,currency:rate?.currency||fallbackCurrency,active:rate?.active??true}})},
 async saveBase(session:AdminSession,roomTypeId:string,price:number,currency:string,active:boolean){const db=await createServerSupabaseClient();const{data:existing}=await db.from('rates').select('id').eq('property_id',session.propertyId).eq('room_type_id',roomTypeId).neq('status','archived').maybeSingle();const values={property_id:session.propertyId,room_type_id:roomTypeId,title:'Base rate',base_price:price,currency,active,status:'published',is_visible:true,updated_by:session.userId};const result=existing?await db.from('rates').update(values).eq('id',existing.id).eq('property_id',session.propertyId):await db.from('rates').insert({...values,created_by:session.userId});if(result.error)throw result.error},
 async listSeasons(session:AdminSession):Promise<SeasonalRate[]>{const db=await createServerSupabaseClient();const[{data,error},{data:links},{data:rooms},{data:property}]=await Promise.all([db.from('seasonal_rate_periods').select('id,name,start_date,end_date,nightly_price,currency,active,status').eq('property_id',session.propertyId).order('start_date'),db.from('seasonal_rate_room_types').select('period_id,room_type_id').eq('property_id',session.propertyId),db.from('room_types').select('id,name').eq('property_id',session.propertyId),db.from('properties').select('currency').eq('id',session.propertyId).single()]);if(error)throw error;const rows=(data||[])as PeriodRow[],fallbackCurrency=property?.currency||'EUR',rules=rows.filter(row=>row.status!=='archived').map(row=>({id:row.id,name:row.name,roomTypeIds:(links||[]).filter(link=>link.period_id===row.id).map(link=>link.room_type_id),startDate:row.start_date,endDate:row.end_date,amount:Number(row.nightly_price),active:row.active})),conflicts=findSeasonalConflicts(rules);return rows.map(row=>{const roomTypeIds=(links||[]).filter(link=>link.period_id===row.id).map(link=>link.room_type_id);return{id:row.id,name:row.name,startDate:row.start_date,endDate:row.end_date,price:Number(row.nightly_price),currency:row.currency||fallbackCurrency,active:row.active,status:row.status,roomTypeIds,roomTypeNames:(rooms||[]).filter(room=>roomTypeIds.includes(room.id)).map(room=>room.name),conflictIds:conflicts.filter(item=>item.firstId===row.id||item.secondId===row.id).map(item=>item.firstId===row.id?item.secondId:item.firstId)}})},
 async saveSeason(session:AdminSession,id:string|null,input:{name:string;startDate:string;endDate:string;currency:string;price:number;active:boolean;roomTypeIds:string[]}){const db=await createServerSupabaseClient(),values={property_id:session.propertyId,name:input.name,start_date:input.startDate,end_date:input.endDate,nightly_price:input.price,currency:input.currency,active:input.active,status:'published',updated_by:session.userId,archived_at:null};const result=id?await db.from('seasonal_rate_periods').update(values).eq('id',id).eq('property_id',session.propertyId).select('id').single():await db.from('seasonal_rate_periods').insert({...values,created_by:session.userId}).select('id').single();if(result.error)throw result.error;const periodId=result.data.id;const deleted=await db.from('seasonal_rate_room_types').delete().eq('period_id',periodId);if(deleted.error)throw deleted.error;const inserted=await db.from('seasonal_rate_room_types').insert(input.roomTypeIds.map(roomTypeId=>({period_id:periodId,room_type_id:roomTypeId,property_id:session.propertyId})));if(inserted.error)throw inserted.error;return periodId},
 async setSeasonStatus(session:AdminSession,id:string,status:'archived'|'published'){const db=await createServerSupabaseClient();const{error}=await db.from('seasonal_rate_periods').update({status,active:status!=='archived',archived_at:status==='archived'?new Date().toISOString():null,updated_by:session.userId}).eq('id',id).eq('property_id',session.propertyId);if(error)throw error},
 async listRules(session:AdminSession):Promise<PricingRule[]>{const db=await createServerSupabaseClient();const{data,error}=await db.from('pricing_rules').select('id,name,room_type_id,rule_type,start_date,end_date,amount,percentage,nights,active,status,room_types(name)').eq('property_id',session.propertyId).order('created_at',{ascending:false});if(error)throw error;return(data||[]).map(row=>({id:row.id,name:row.name,roomTypeId:row.room_type_id,roomTypeName:(row.room_types as unknown as {name:string}|null)?.name||'All room types',type:row.rule_type,startDate:row.start_date||'',endDate:row.end_date||'',amount:row.amount===null?null:Number(row.amount),percentage:row.percentage===null?null:Number(row.percentage),nights:row.nights,active:row.active,status:row.status}))},
 async saveRule(session:AdminSession,input:{name:string;type:string;roomTypeId:string|null;startDate:string|null;endDate:string|null;value:number;active:boolean}){const db=await createServerSupabaseClient();const isPercent=input.type==='discount_percentage',isNights=['minimum_stay','maximum_stay'].includes(input.type),isClosed=['closed_to_arrival','closed_to_departure'].includes(input.type);const{error}=await db.from('pricing_rules').insert({property_id:session.propertyId,name:input.name,rule_type:input.type,room_type_id:input.roomTypeId,start_date:input.startDate,end_date:input.endDate,amount:!isPercent&&!isNights&&!isClosed?input.value:null,percentage:isPercent?input.value:null,nights:isNights?input.value:null,active:input.active,status:'published',created_by:session.userId,updated_by:session.userId});if(error)throw error},
 async setRuleStatus(session:AdminSession,id:string,status:'archived'|'published'){const db=await createServerSupabaseClient();const{error}=await db.from('pricing_rules').update({status,active:status!=='archived',archived_at:status==='archived'?new Date().toISOString():null,updated_by:session.userId}).eq('id',id).eq('property_id',session.propertyId);if(error)throw error}
};
