import 'server-only';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { resolvePublicMediaUrl } from '@/lib/media-url';
import type { AdminSession } from '@/lib/admin/auth';
import type { PhysicalRoomInput, RoomTypeInput } from '@/lib/admin/room-validation';
import type { AdminAmenity, AdminPhysicalRoom, AdminRoomImage, AdminRoomType } from '@/types/rooms-admin';
type RoomTypeRow={id:string;name:string;slug:string|null;short_description:string|null;long_description:string|null;capacity:number;adults:number;children:number;beds:number;bed_configuration:string|null;size_sqm:number|null;view_type:string|null;base_occupancy:number;inventory_count:number;is_featured:boolean;is_visible:boolean;status:'draft'|'published'|'archived';sort_order:number;updated_at:string};
type ImageRow={id:string;room_type_id:string;media_asset_id:string;sort_order:number;is_featured:boolean;status:'draft'|'published'|'archived';media_assets:{file_path:string;alt_text:string|null}|null};

export const adminRoomsRepository={
async listAmenities(session:AdminSession):Promise<AdminAmenity[]>{const db=await createServerSupabaseClient();const{data,error}=await db.from('amenities').select('id,name,icon').eq('property_id',session.propertyId).neq('status','archived').eq('active',true).order('sort_order');if(error)return[];return data||[]},
async listRoomTypes(session:AdminSession):Promise<AdminRoomType[]>{const db=await createServerSupabaseClient();const[{data:types,error},{data:rates},{data:seo},{data:links},{data:images}]=await Promise.all([db.from('room_types').select('id,name,slug,short_description,long_description,capacity,adults,children,beds,bed_configuration,size_sqm,view_type,base_occupancy,inventory_count,is_featured,is_visible,status,sort_order,updated_at').eq('property_id',session.propertyId).order('sort_order'),db.from('rates').select('room_type_id,base_price,currency,created_at').eq('property_id',session.propertyId).neq('status','archived').order('created_at'),db.from('seo_metadata').select('entity_id,title,meta_description').eq('property_id',session.propertyId).eq('entity_type','room_type'),db.from('room_type_amenities').select('room_type_id,amenity_id').eq('property_id',session.propertyId),db.from('room_images').select('id,room_type_id,media_asset_id,sort_order,is_featured,status,media_assets(file_path,alt_text)').eq('property_id',session.propertyId).order('sort_order')]);if(error)throw error;return((types||[]) as RoomTypeRow[]).map(row=>{const price=(rates||[]).find(item=>item.room_type_id===row.id);const meta=(seo||[]).find(item=>item.entity_id===row.id);const roomImages=((images||[]) as unknown as ImageRow[]).filter(item=>item.room_type_id===row.id&&item.media_assets).map((item):AdminRoomImage=>({id:item.id,mediaAssetId:item.media_asset_id,filePath:item.media_assets!.file_path,publicUrl:resolvePublicMediaUrl(item.media_assets!.file_path),altText:item.media_assets!.alt_text||'',sortOrder:item.sort_order,isFeatured:item.is_featured,status:item.status}));return{id:row.id,name:row.name,slug:row.slug||'',shortDescription:row.short_description||'',longDescription:row.long_description||'',capacity:row.capacity,adults:row.adults,children:row.children,beds:row.beds,bedConfiguration:row.bed_configuration||'',sizeSqm:row.size_sqm===null?null:Number(row.size_sqm),viewType:row.view_type||'',baseOccupancy:row.base_occupancy,inventoryCount:row.inventory_count||1,featured:row.is_featured,visible:row.is_visible,status:row.status,sortOrder:row.sort_order,basePrice:price?Number(price.base_price):null,currency:price?.currency||'EUR',seoTitle:meta?.title||'',seoDescription:meta?.meta_description||'',amenityIds:(links||[]).filter(item=>item.room_type_id===row.id).map(item=>item.amenity_id),images:roomImages,updatedAt:row.updated_at}})},
async getRoomType(session:AdminSession,id:string){return(await this.listRoomTypes(session)).find(item=>item.id===id)||null},
async saveRoomType(session:AdminSession,id:string|null,input:RoomTypeInput){const db=await createServerSupabaseClient();const values={property_id:session.propertyId,name:input.name,title:input.name,slug:input.slug,short_description:input.shortDescription,long_description:input.longDescription,description:input.shortDescription,capacity:input.capacity,adults:input.adults,children:input.children,beds:input.beds,bed_configuration:input.bedConfiguration,size_sqm:input.sizeSqm,view_type:input.viewType,base_occupancy:input.baseOccupancy,is_featured:input.featured,is_visible:input.visible,status:input.status,sort_order:input.sortOrder,updated_by:session.userId,archived_at:null};const result=id?await db.from('room_types').update(values).eq('id',id).eq('property_id',session.propertyId).select('id').single():await db.from('room_types').insert({...values,created_by:session.userId}).select('id').single();if(result.error)throw result.error;const roomTypeId=result.data.id;const{error:inventoryError}=await db.rpc('sync_room_inventory',{target_room_type:roomTypeId,target_count:input.inventoryCount,actor:session.userId});if(inventoryError)throw inventoryError;await db.from('room_type_amenities').delete().eq('room_type_id',roomTypeId);if(input.amenityIds.length){const{error}=await db.from('room_type_amenities').insert(input.amenityIds.map(amenityId=>({property_id:session.propertyId,room_type_id:roomTypeId,amenity_id:amenityId,created_by:session.userId})));if(error)throw error}const{data:rate}=await db.from('rates').select('id').eq('property_id',session.propertyId).eq('room_type_id',roomTypeId).neq('status','archived').maybeSingle();if(input.basePrice!==null){const rateValues={property_id:session.propertyId,room_type_id:roomTypeId,title:'Base rate',base_price:input.basePrice,currency:input.currency,status:input.status,is_visible:input.visible,updated_by:session.userId};const rateResult=rate?await db.from('rates').update(rateValues).eq('id',rate.id):await db.from('rates').insert({...rateValues,created_by:session.userId});if(rateResult.error)throw rateResult.error}const seoValues={property_id:session.propertyId,entity_type:'room_type',entity_id:roomTypeId,title:input.seoTitle||null,meta_description:input.seoDescription||null,status:input.status,updated_by:session.userId};const{error:seoError}=await db.from('seo_metadata').upsert({...seoValues,created_by:session.userId},{onConflict:'property_id,entity_type,entity_id'});if(seoError)throw seoError;return roomTypeId},
async setRoomTypeStatus(session:AdminSession,id:string,status:'archived'|'draft'){const db=await createServerSupabaseClient();const room=await this.getRoomType(session,id);if(!room)throw new Error('Room not found');const{error}=await db.from('room_types').update({status,archived_at:status==='archived'?new Date().toISOString():null,is_visible:status!=='archived',updated_by:session.userId}).eq('id',id).eq('property_id',session.propertyId);if(error)throw error;const{error:inventoryError}=await db.rpc('sync_room_inventory',{target_room_type:id,target_count:room.inventoryCount,actor:session.userId});if(inventoryError)throw inventoryError},
async duplicateRoomType(session:AdminSession,id:string){const source=await this.getRoomType(session,id);if(!source)throw new Error('Room not found');return this.saveRoomType(session,null,{name:`${source.name} copy`,slug:`${source.slug}-copy-${Date.now().toString().slice(-5)}`,shortDescription:source.shortDescription,longDescription:source.longDescription,capacity:source.capacity,adults:source.adults,children:source.children,beds:source.beds,bedConfiguration:source.bedConfiguration,sizeSqm:source.sizeSqm,viewType:source.viewType,baseOccupancy:source.baseOccupancy,inventoryCount:source.inventoryCount,featured:false,visible:false,status:'draft',sortOrder:source.sortOrder+1,basePrice:source.basePrice,currency:source.currency,seoTitle:source.seoTitle,seoDescription:source.seoDescription,amenityIds:source.amenityIds})},
async listPhysicalRooms(session:AdminSession):Promise<AdminPhysicalRoom[]>{const db=await createServerSupabaseClient();const{data,error}=await db.from('rooms').select('id,room_number,title,room_type_id,active,notes,availability_status,status,room_types(name)').eq('property_id',session.propertyId).order('room_number');if(error)return[];return(data||[]).map(row=>({id:row.id,internalName:row.title||row.room_number,roomTypeId:row.room_type_id,roomTypeName:(row.room_types as unknown as {name:string}|null)?.name||'Unassigned',active:row.active,notes:row.notes||'',availabilityStatus:row.availability_status,status:row.status}))},
async getPhysicalRoom(session:AdminSession,id:string){return(await this.listPhysicalRooms(session)).find(item=>item.id===id)||null},
async savePhysicalRoom(session:AdminSession,id:string|null,input:PhysicalRoomInput){const db=await createServerSupabaseClient();const values={property_id:session.propertyId,room_type_id:input.roomTypeId,room_number:input.internalName,title:input.internalName,active:input.active,is_available:input.availabilityStatus==='available',availability_status:input.availabilityStatus,notes:input.notes,status:input.status,is_visible:input.active,updated_by:session.userId,archived_at:null};const result=id?await db.from('rooms').update(values).eq('id',id).eq('property_id',session.propertyId).select('id').single():await db.from('rooms').insert({...values,created_by:session.userId}).select('id').single();if(result.error)throw result.error;return result.data.id},
async setPhysicalRoomStatus(session:AdminSession,id:string,status:'archived'|'draft'){const db=await createServerSupabaseClient();const{error}=await db.from('rooms').update({status,active:status!=='archived',is_visible:status!=='archived',archived_at:status==='archived'?new Date().toISOString():null,updated_by:session.userId}).eq('id',id).eq('property_id',session.propertyId);if(error)throw error},
};
