import'server-only';
import{createServerSupabaseClient}from'@/lib/supabase/server';
import type{AdminSession}from'@/lib/admin/auth';
import type{AdminTransfer,TransferMediaOption}from'@/types/transfers-admin';
import type{validateTransfer}from'@/lib/admin/transfer-validation';
type Input=NonNullable<ReturnType<typeof validateTransfer>['data']>;
type Row={id:string;origin:string;destination:string;slug:string;short_description:string|null;description:string|null;full_description:string|null;cover_media_id:string|null;duration_label:string|null;duration_minutes:number|null;capacity:number|null;service_type:string|null;price:number|string|null;currency:string|null;price_type:string;booking_notice:string|null;active:boolean;is_featured:boolean;bookable:boolean;status:'draft'|'published'|'archived';sort_order:number;availability_mode:string;available_days:number[]|null;window_start:string|null;window_end:string|null;updated_at:string};
const publicUrl=(base:string,path:string)=>`${base}/storage/v1/object/public/public-media/${path}`;
export const adminTransfersRepository={
  async list(session:AdminSession):Promise<AdminTransfer[]>{const db=await createServerSupabaseClient(),base=process.env.NEXT_PUBLIC_SUPABASE_URL||'';const[{data,error},{data:images},{data:media},{data:seo}]=await Promise.all([db.from('transfer_routes').select('id,origin,destination,slug,short_description,description,full_description,cover_media_id,duration_label,duration_minutes,capacity,service_type,price,currency,price_type,booking_notice,active,is_featured,bookable,status,sort_order,availability_mode,available_days,window_start,window_end,updated_at').eq('property_id',session.propertyId).order('sort_order'),db.from('transfer_images').select('transfer_route_id,media_asset_id,sort_order').eq('property_id',session.propertyId).neq('status','archived').order('sort_order'),db.from('media_assets').select('id,file_path').eq('property_id',session.propertyId).neq('status','archived'),db.from('seo_metadata').select('entity_id,title,meta_description').eq('property_id',session.propertyId).eq('entity_type','transfer_route')]);if(error)throw error;const paths=new Map((media||[]).map(item=>[item.id,item.file_path]));return((data||[])as Row[]).map(row=>{const gallery=(images||[]).filter(item=>item.transfer_route_id===row.id),meta=(seo||[]).find(item=>item.entity_id===row.id),coverPath=paths.get(row.cover_media_id||'')||paths.get(gallery[0]?.media_asset_id||'');return{id:row.id,origin:row.origin,destination:row.destination,slug:row.slug,shortDescription:row.short_description||row.description||'',fullDescription:row.full_description||'',coverMediaId:row.cover_media_id||'',imageUrl:coverPath?publicUrl(base,coverPath):'',galleryMediaIds:gallery.map(item=>item.media_asset_id),duration:row.duration_label||(row.duration_minutes?`${row.duration_minutes} minutes`:''),capacity:row.capacity,serviceType:row.service_type||'',price:row.price===null?null:Number(row.price),currency:row.currency||'EUR',pricingMethod:(row.price_type==='per_passenger'||row.price_type==='on_request'?row.price_type:'fixed_vehicle'),bookingNotice:row.booking_notice||'',active:row.active,featured:row.is_featured,bookable:row.bookable,status:row.status,sortOrder:row.sort_order,availabilityMode:(row.availability_mode==='always'||row.availability_mode==='scheduled'?row.availability_mode:'on_request'),availableDays:row.available_days||[],windowStart:(row.window_start||'').slice(0,5),windowEnd:(row.window_end||'').slice(0,5),seoTitle:meta?.title||'',seoDescription:meta?.meta_description||'',updatedAt:row.updated_at}})},
  async get(session:AdminSession,id:string){return(await this.list(session)).find(item=>item.id===id)||null},
  async media(session:AdminSession):Promise<TransferMediaOption[]>{const db=await createServerSupabaseClient(),base=process.env.NEXT_PUBLIC_SUPABASE_URL||'';const{data}=await db.from('media_assets').select('id,filename,alt_text,file_path').eq('property_id',session.propertyId).neq('status','archived').order('sort_order');return(data||[]).map(item=>({id:item.id,label:item.alt_text||item.filename,url:publicUrl(base,item.file_path)}))},
  async save(session:AdminSession,id:string|null,input:Input){const db=await createServerSupabaseClient(),values={property_id:session.propertyId,title:`${input.origin} to ${input.destination}`,origin:input.origin,destination:input.destination,slug:input.slug,description:input.shortDescription,short_description:input.shortDescription,full_description:input.fullDescription,cover_media_id:input.coverMediaId,duration_label:input.duration,capacity:input.capacity,service_type:input.serviceType,price:input.price,currency:input.currency,price_type:input.pricingMethod,booking_notice:input.bookingNotice,active:input.active,is_featured:input.featured,is_visible:input.active,bookable:input.bookable,status:input.status,sort_order:input.sortOrder,availability_mode:input.availabilityMode,available_days:input.availableDays,window_start:input.windowStart,window_end:input.windowEnd,updated_by:session.userId,archived_at:null};const result=id?await db.from('transfer_routes').update(values).eq('id',id).eq('property_id',session.propertyId).select('id').single():await db.from('transfer_routes').insert({...values,created_by:session.userId}).select('id').single();if(result.error)throw result.error;const transferId=result.data.id;await db.from('transfer_images').delete().eq('transfer_route_id',transferId);const ids=Array.from(new Set([input.coverMediaId,...input.galleryMediaIds].filter(Boolean)))as string[];if(ids.length){const{error}=await db.from('transfer_images').insert(ids.map((mediaId,index)=>({property_id:session.propertyId,transfer_route_id:transferId,media_asset_id:mediaId,sort_order:index,is_featured:mediaId===input.coverMediaId,is_visible:true,status:input.status,created_by:session.userId,updated_by:session.userId})));if(error)throw error}const{error:seoError}=await db.from('seo_metadata').upsert({property_id:session.propertyId,entity_type:'transfer_route',entity_id:transferId,title:input.seoTitle||`${input.origin} to ${input.destination} transfer`,meta_description:input.seoDescription||input.shortDescription,status:input.status,created_by:session.userId,updated_by:session.userId},{onConflict:'property_id,entity_type,entity_id'});if(seoError)throw seoError;return transferId},
  async status(session:AdminSession,id:string,status:'draft'|'archived'){const db=await createServerSupabaseClient();const{error}=await db.from('transfer_routes').update({status,active:false,is_visible:false,archived_at:status==='archived'?new Date().toISOString():null,updated_by:session.userId}).eq('id',id).eq('property_id',session.propertyId);if(error)throw error},
  async duplicate(session:AdminSession,id:string){const item=await this.get(session,id);if(!item)throw new Error('Transfer route not found.');return this.save(session,null,{...item,slug:`${item.slug}-copy-${Date.now().toString().slice(-5)}`,coverMediaId:item.coverMediaId||null,featured:false,active:false,bookable:false,status:'draft',windowStart:item.windowStart||null,windowEnd:item.windowEnd||null})}
};
