'use server';
import{revalidatePath}from'next/cache';import{after}from'next/server';import{requireAdmin}from'@/lib/admin/auth';import{adminBookingsRepository}from'@/lib/repositories/admin/bookings';import{notificationService}from'@/lib/notifications/service';import type{ManagedBookingStatus}from'@/types/bookings-admin';
export type BookingMutationState={ok:boolean;message:string};
export async function changeBookingStatus(id:string,_previous:BookingMutationState,d:FormData):Promise<BookingMutationState>{try{const s=await requireAdmin(['owner','manager','staff']),status=String(d.get('status'))as ManagedBookingStatus;await adminBookingsRepository.updateStatus(s,id,status);if(status==='cancelled')after(async()=>{try{await notificationService.dispatchForBooking(id,'booking_cancelled')}catch(error){console.error('Cancellation notification failed:',error)}});revalidatePath('/admin/bookings');revalidatePath(`/admin/bookings/${id}`);revalidatePath('/admin/availability');revalidatePath('/book');revalidatePath('/rooms');revalidatePath('/');return{ok:true,message:`Booking status changed to ${status.replaceAll('_',' ')}.`}}catch(error){return{ok:false,message:error instanceof Error?error.message:'The booking status could not be changed.'}}}
export async function saveBookingNote(id:string,_previous:BookingMutationState,d:FormData):Promise<BookingMutationState>{try{const s=await requireAdmin(['owner','manager','staff']);await adminBookingsRepository.saveNote(s,id,String(d.get('internalNote')||'').trim());revalidatePath(`/admin/bookings/${id}`);return{ok:true,message:'Internal note saved.'}}catch(error){return{ok:false,message:error instanceof Error?error.message:'The note could not be saved.'}}}
export type ManualBookingState={ok:boolean;message:string;id?:string;values?:Record<string,string>};
export async function createManualBooking(_previous:ManualBookingState,d:FormData):Promise<ManualBookingState>{
 const s=await requireAdmin(['owner','manager','staff']),value=(key:string)=>String(d.get(key)||'').trim(),values=Object.fromEntries(['roomTypeId','checkIn','checkOut','adults','children','infants','firstName','lastName','email','phone','country','notes'].map(key=>[key,value(key)]));
 const adults=Number(values.adults),children=Number(values.children),infants=Number(values.infants);if(!values.roomTypeId||!values.checkIn||!values.checkOut||values.checkOut<=values.checkIn||!Number.isInteger(adults)||adults<1||!Number.isInteger(children)||children<0||!Number.isInteger(infants)||infants<0||!values.firstName||!values.lastName||!values.phone||!/^\S+@\S+\.\S+$/.test(values.email))return{ok:false,message:'Complete the room, valid dates, adult, child and infant counts, and contact details.',values};
 try{const result=await adminBookingsRepository.createManual(s,{roomTypeId:values.roomTypeId,checkIn:values.checkIn,checkOut:values.checkOut,adults,children,infants,firstName:values.firstName,lastName:values.lastName,email:values.email,phone:values.phone,country:values.country,notes:values.notes});after(async()=>{try{await notificationService.dispatchForBooking(result.id,'booking_created')}catch(error){console.error('Manual booking notification failed:',error)}});revalidatePath('/admin/bookings');revalidatePath('/admin/availability');return{ok:true,message:`Booking ${result.reference} created.`,id:result.id}}catch(error){const message=error instanceof Error?error.message:typeof error==='object'&&error&&'message'in error?String(error.message):'The manual booking could not be created.';return{ok:false,message,values}}
}
