import Link from 'next/link';
import { requireAdmin } from '@/lib/admin/auth';
import { adminBookingsRepository } from '@/lib/repositories/admin/bookings';
import { AdminEmptyState, AdminPageHeader, StatusBadge } from '@/components/admin/ui';
import { formatMoney } from '@/lib/pricing/format';

const statuses=['','held','pending','awaiting_payment','confirmed','cancelled','checked_in','completed'];
type BookingRow=Awaited<ReturnType<typeof adminBookingsRepository.list>>[number];
export default async function BookingsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;period?:string;room?:string;from?:string;to?:string}>}){
  const session=await requireAdmin(['owner','manager','staff']),filters=await searchParams;
  const[bookings,rooms]=await Promise.all([adminBookingsRepository.list(session,{query:filters.q,status:filters.status,period:filters.period,roomTypeId:filters.room,from:filters.from,to:filters.to}),adminBookingsRepository.rooms(session)]);
  return <div className="space-y-7"><AdminPageHeader title="Bookings" description="Search room, package and standalone service bookings in one operational list." actions={<Link href="/admin/bookings/new" className="inline-flex min-h-11 items-center justify-center rounded-lg bg-slate-950 px-4 text-sm font-bold text-white">Add booking</Link>}/>
    <nav aria-label="Booking periods" className="flex gap-2 overflow-x-auto pb-1">{[['','All'],['upcoming','Upcoming'],['current','Current'],['past','Past'],['cancelled','Cancelled']].map(([value,label])=><Link key={label} href={value?`/admin/bookings?period=${value}`:'/admin/bookings'} className={`inline-flex min-h-11 shrink-0 items-center rounded-full px-4 py-2 text-sm font-bold ${filters.period===value||(!filters.period&&!value)?'bg-cyan-900 text-white':'border border-slate-300 bg-white text-slate-700'}`}>{label}</Link>)}</nav>
    <details className="group rounded-2xl border border-slate-200 bg-white md:hidden"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between px-4 font-bold"><span>Search and filters</span><span aria-hidden="true" className="text-lg group-open:rotate-180">⌄</span></summary><div className="border-t border-slate-100 p-4"><BookingFilters filters={filters} rooms={rooms}/></div></details>
    <BookingFilters filters={filters} rooms={rooms} desktop/>
    {bookings.length?<><MobileBookings bookings={bookings}/><div className="hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white md:block"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Reference</th><th className="p-4">Guest</th><th className="p-4">Type</th><th className="p-4">Booking content</th><th className="p-4">Date / time</th><th className="p-4">Quantity</th><th className="p-4">Total</th><th className="p-4">Status</th><th className="p-4">Source</th><th/></tr></thead><tbody>{bookings.map(booking=><tr key={booking.id} className="border-t border-slate-100"><td className="p-4 font-bold">{booking.reference}</td><td className="p-4">{booking.guestName}<span className="block text-xs text-slate-500">{booking.email}</span></td><td className="p-4 font-semibold">{booking.bookingType}</td><td className="p-4">{booking.room}</td><td className="p-4">{booking.checkIn&&booking.checkOut?`${booking.checkIn} → ${booking.checkOut}`:<>{booking.serviceDate||'Not scheduled'}{booking.serviceTime&&<span className="block text-xs text-slate-500">{booking.serviceTime}</span>}</>}</td><td className="p-4">{booking.quantity||booking.adults+booking.children}</td><td className="p-4 font-semibold">{formatMoney(booking.total,booking.currency)}</td><td className="p-4"><StatusBadge status={booking.status}/></td><td className="p-4 capitalize">{booking.source}</td><td className="p-4"><Link href={`/admin/bookings/${booking.id}`} className="inline-flex min-h-11 items-center font-bold underline">Open</Link></td></tr>)}</tbody></table></div></>:<AdminEmptyState title="No matching bookings" description="New website reservations and manual bookings will appear here." action={<Link href="/admin/bookings/new" className="inline-flex min-h-11 items-center justify-center rounded-lg bg-slate-950 px-4 text-sm font-bold text-white">Add booking</Link>}/>}</div>;
}

function BookingFilters({filters,rooms,desktop=false}:{filters:{q?:string;status?:string;period?:string;room?:string;from?:string;to?:string};rooms:Awaited<ReturnType<typeof adminBookingsRepository.rooms>>;desktop?:boolean}){return <form className={`${desktop?'hidden md:grid':'grid'} gap-3 rounded-2xl border-slate-200 bg-white md:grid-cols-2 xl:grid-cols-[1.5fr_1fr_1fr_1fr_1fr_auto] ${desktop?'border p-4':''}`}><input type="hidden" name="period" value={filters.period||''}/><input name="q" defaultValue={filters.q} placeholder="Reference, guest, email or booking content" aria-label="Search bookings" className="min-h-11 rounded-lg border border-slate-300 px-3"/><select name="status" aria-label="Booking status" defaultValue={filters.status} className="min-h-11 rounded-lg border border-slate-300 px-3">{statuses.map(value=><option key={value} value={value}>{value?value.replaceAll('_',' '):'All statuses'}</option>)}</select><select name="room" aria-label="Room" defaultValue={filters.room} className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="">All rooms</option>{rooms.map(room=><option key={room.id} value={room.id}>{room.name}</option>)}</select><input name="from" type="date" defaultValue={filters.from} aria-label="Service date from" className="min-h-11 rounded-lg border border-slate-300 px-3"/><input name="to" type="date" defaultValue={filters.to} aria-label="Service date to" className="min-h-11 rounded-lg border border-slate-300 px-3"/><button className="min-h-11 rounded-lg bg-cyan-900 px-5 font-bold text-white">Apply filters</button></form>}

function MobileBookings({bookings}:{bookings:BookingRow[]}){
  return <section aria-label="Bookings" className="grid gap-3 md:hidden">{bookings.map(booking=><article key={booking.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
    <div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-bold text-slate-950">{booking.reference}</p><p className="truncate text-sm font-semibold text-slate-700">{booking.guestName}</p></div><StatusBadge status={booking.status}/></div>
    <dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 text-sm">
      <MobileFact label="Type" value={booking.bookingType}/><MobileFact label="Total" value={formatMoney(booking.total,booking.currency)}/>
      <MobileFact label="Date" value={booking.checkIn&&booking.checkOut?`${booking.checkIn} – ${booking.checkOut}`:`${booking.serviceDate||'Not scheduled'}${booking.serviceTime?` · ${booking.serviceTime}`:''}`}/>
      <MobileFact label="Source" value={booking.source}/><div className="col-span-2"><MobileFact label="Booking" value={booking.room}/></div>
    </dl>
    <Link href={`/admin/bookings/${booking.id}`} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-lg bg-slate-950 px-4 text-sm font-bold text-white">View booking</Link>
  </article>)}</section>;
}
function MobileFact({label,value}:{label:string;value:string}){return <div className="min-w-0"><dt className="text-[.65rem] font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-0.5 break-words font-semibold capitalize text-slate-800">{value}</dd></div>}
