'use server';
import { revalidatePath } from 'next/cache';import { requireAdmin } from '@/lib/admin/auth';import { validatePhysicalRoom,validateRoomType } from '@/lib/admin/room-validation';import { adminRoomsRepository } from '@/lib/repositories/admin/rooms';import type { RoomFormState } from '@/types/rooms-admin';
const refresh=()=>{revalidatePath('/admin/rooms');revalidatePath('/rooms');revalidatePath('/')};
export async function saveRoomType(_:RoomFormState,data:FormData):Promise<RoomFormState>{const session=await requireAdmin(['owner','manager','editor']);const validated=validateRoomType(data);if(!validated.data)return validated.state!;try{const id=await adminRoomsRepository.saveRoomType(session,String(data.get('id')||'')||null,validated.data);refresh();return{ok:true,message:validated.data.status==='published'?'Room saved and published.':'Room draft saved.',id}}catch(error){return{ok:false,message:error instanceof Error?error.message:'Room could not be saved.'}}}
export async function savePhysicalRoom(_:RoomFormState,data:FormData):Promise<RoomFormState>{const session=await requireAdmin(['owner','manager']);const validated=validatePhysicalRoom(data);if(!validated.data)return validated.state!;try{const id=await adminRoomsRepository.savePhysicalRoom(session,String(data.get('id')||'')||null,validated.data);refresh();return{ok:true,message:'Physical room saved.',id}}catch(error){return{ok:false,message:error instanceof Error?error.message:'Physical room could not be saved.'}}}
export async function archiveRoomType(id:string){const session=await requireAdmin(['owner','manager','editor']);await adminRoomsRepository.setRoomTypeStatus(session,id,'archived');refresh()}
export async function restoreRoomType(id:string){const session=await requireAdmin(['owner','manager','editor']);await adminRoomsRepository.setRoomTypeStatus(session,id,'draft');refresh()}
export async function duplicateRoomType(id:string){const session=await requireAdmin(['owner','manager','editor']);await adminRoomsRepository.duplicateRoomType(session,id);refresh()}
export async function archivePhysicalRoom(id:string){const session=await requireAdmin(['owner','manager']);await adminRoomsRepository.setPhysicalRoomStatus(session,id,'archived');refresh()}
export async function restorePhysicalRoom(id:string){const session=await requireAdmin(['owner','manager']);await adminRoomsRepository.setPhysicalRoomStatus(session,id,'draft');refresh()}
